/**
 * This class is generated by jOOQ
 */
package io.github.bfvstats.game.jooq;


import io.github.bfvstats.game.jooq.tables.Player;
import io.github.bfvstats.game.jooq.tables.PlayerNickname;
import io.github.bfvstats.game.jooq.tables.Round;
import io.github.bfvstats.game.jooq.tables.RoundChatLog;
import io.github.bfvstats.game.jooq.tables.RoundEndStats;
import io.github.bfvstats.game.jooq.tables.RoundEndStatsPlayer;
import io.github.bfvstats.game.jooq.tables.RoundPlayerScoreEvent;
import io.github.bfvstats.game.jooq.tables.SqliteSequence;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>player</code>.
     */
    public static final Player PLAYER = io.github.bfvstats.game.jooq.tables.Player.PLAYER;

    /**
     * The table <code>player_nickname</code>.
     */
    public static final PlayerNickname PLAYER_NICKNAME = io.github.bfvstats.game.jooq.tables.PlayerNickname.PLAYER_NICKNAME;

    /**
     * The table <code>round</code>.
     */
    public static final Round ROUND = io.github.bfvstats.game.jooq.tables.Round.ROUND;

    /**
     * The table <code>round_chat_log</code>.
     */
    public static final RoundChatLog ROUND_CHAT_LOG = io.github.bfvstats.game.jooq.tables.RoundChatLog.ROUND_CHAT_LOG;

    /**
     * The table <code>round_end_stats</code>.
     */
    public static final RoundEndStats ROUND_END_STATS = io.github.bfvstats.game.jooq.tables.RoundEndStats.ROUND_END_STATS;

    /**
     * The table <code>round_end_stats_player</code>.
     */
    public static final RoundEndStatsPlayer ROUND_END_STATS_PLAYER = io.github.bfvstats.game.jooq.tables.RoundEndStatsPlayer.ROUND_END_STATS_PLAYER;

    /**
     * The table <code>round_player_score_event</code>.
     */
    public static final RoundPlayerScoreEvent ROUND_PLAYER_SCORE_EVENT = io.github.bfvstats.game.jooq.tables.RoundPlayerScoreEvent.ROUND_PLAYER_SCORE_EVENT;

    /**
     * The table <code>sqlite_sequence</code>.
     */
    public static final SqliteSequence SQLITE_SEQUENCE = io.github.bfvstats.game.jooq.tables.SqliteSequence.SQLITE_SEQUENCE;
}
