/*
 * This file is generated by jOOQ.
*/
package io.github.bfstats.game.jooq.tables;


import io.github.bfstats.game.jooq.DefaultSchema;
import io.github.bfstats.game.jooq.Indexes;
import io.github.bfstats.game.jooq.Keys;
import io.github.bfstats.game.jooq.tables.records.RoundChatLogRecord;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoundChatLog extends TableImpl<RoundChatLogRecord> {

    private static final long serialVersionUID = -1605093111;

    /**
     * The reference instance of <code>round_chat_log</code>
     */
    public static final RoundChatLog ROUND_CHAT_LOG = new RoundChatLog();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RoundChatLogRecord> getRecordType() {
        return RoundChatLogRecord.class;
    }

    /**
     * The column <code>round_chat_log.id</code>.
     */
    public final TableField<RoundChatLogRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>round_chat_log.round_id</code>.
     */
    public final TableField<RoundChatLogRecord, Integer> ROUND_ID = createField("round_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>round_chat_log.player_id</code>.
     */
    public final TableField<RoundChatLogRecord, Integer> PLAYER_ID = createField("player_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>round_chat_log.player_location_x</code>.
     */
    public final TableField<RoundChatLogRecord, BigDecimal> PLAYER_LOCATION_X = createField("player_location_x", org.jooq.impl.SQLDataType.NUMERIC(4, 4), this, "");

    /**
     * The column <code>round_chat_log.player_location_y</code>.
     */
    public final TableField<RoundChatLogRecord, BigDecimal> PLAYER_LOCATION_Y = createField("player_location_y", org.jooq.impl.SQLDataType.NUMERIC(4, 4), this, "");

    /**
     * The column <code>round_chat_log.player_location_z</code>.
     */
    public final TableField<RoundChatLogRecord, BigDecimal> PLAYER_LOCATION_Z = createField("player_location_z", org.jooq.impl.SQLDataType.NUMERIC(4, 4), this, "");

    /**
     * The column <code>round_chat_log.to_team</code>.
     */
    public final TableField<RoundChatLogRecord, Integer> TO_TEAM = createField("to_team", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>round_chat_log.message</code>.
     */
    public final TableField<RoundChatLogRecord, String> MESSAGE = createField("message", org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>round_chat_log.event_time</code>.
     */
    public final TableField<RoundChatLogRecord, Timestamp> EVENT_TIME = createField("event_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * Create a <code>round_chat_log</code> table reference
     */
    public RoundChatLog() {
        this(DSL.name("round_chat_log"), null);
    }

    /**
     * Create an aliased <code>round_chat_log</code> table reference
     */
    public RoundChatLog(String alias) {
        this(DSL.name(alias), ROUND_CHAT_LOG);
    }

    /**
     * Create an aliased <code>round_chat_log</code> table reference
     */
    public RoundChatLog(Name alias) {
        this(alias, ROUND_CHAT_LOG);
    }

    private RoundChatLog(Name alias, Table<RoundChatLogRecord> aliased) {
        this(alias, aliased, null);
    }

    private RoundChatLog(Name alias, Table<RoundChatLogRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ROUND_CHAT_LOG_PLAYER_ID_IDX, Indexes.ROUND_CHAT_LOG_ROUND_ID_IDX);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<RoundChatLogRecord, Integer> getIdentity() {
        return Keys.IDENTITY_ROUND_CHAT_LOG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RoundChatLogRecord> getPrimaryKey() {
        return Keys.PK_ROUND_CHAT_LOG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RoundChatLogRecord>> getKeys() {
        return Arrays.<UniqueKey<RoundChatLogRecord>>asList(Keys.PK_ROUND_CHAT_LOG);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<RoundChatLogRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<RoundChatLogRecord, ?>>asList(Keys.FK_ROUND_CHAT_LOG_ROUND_1, Keys.FK_ROUND_CHAT_LOG_PLAYER_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoundChatLog as(String alias) {
        return new RoundChatLog(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoundChatLog as(Name alias) {
        return new RoundChatLog(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RoundChatLog rename(String name) {
        return new RoundChatLog(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RoundChatLog rename(Name name) {
        return new RoundChatLog(name, null);
    }
}
