/**
 * This class is generated by jOOQ
 */
package io.github.bfvstats.jpa.tables;


import io.github.bfvstats.jpa.DefaultSchema;
import io.github.bfvstats.jpa.tables.records.SelectbfClanTagsRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SelectbfClanTags extends TableImpl<SelectbfClanTagsRecord> {

    private static final long serialVersionUID = 633503855;

    /**
     * The reference instance of <code>selectbf_clan_tags</code>
     */
    public static final SelectbfClanTags SELECTBF_CLAN_TAGS = new SelectbfClanTags();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SelectbfClanTagsRecord> getRecordType() {
        return SelectbfClanTagsRecord.class;
    }

    /**
     * The column <code>selectbf_clan_tags.clan_tag</code>.
     */
    public final TableField<SelectbfClanTagsRecord, String> CLAN_TAG = createField("clan_tag", org.jooq.impl.SQLDataType.VARCHAR.length(100).defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * Create a <code>selectbf_clan_tags</code> table reference
     */
    public SelectbfClanTags() {
        this("selectbf_clan_tags", null);
    }

    /**
     * Create an aliased <code>selectbf_clan_tags</code> table reference
     */
    public SelectbfClanTags(String alias) {
        this(alias, SELECTBF_CLAN_TAGS);
    }

    private SelectbfClanTags(String alias, Table<SelectbfClanTagsRecord> aliased) {
        this(alias, aliased, null);
    }

    private SelectbfClanTags(String alias, Table<SelectbfClanTagsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelectbfClanTags as(String alias) {
        return new SelectbfClanTags(alias, this);
    }

    /**
     * Rename this table
     */
    public SelectbfClanTags rename(String name) {
        return new SelectbfClanTags(name, null);
    }
}
