/**
 * This class is generated by jOOQ
 */
package io.github.bfvstats.jpa.tables;


import io.github.bfvstats.jpa.DefaultSchema;
import io.github.bfvstats.jpa.Keys;
import io.github.bfvstats.jpa.tables.records.SelectbfTksRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SelectbfTks extends TableImpl<SelectbfTksRecord> {

    private static final long serialVersionUID = -1111325749;

    /**
     * The reference instance of <code>selectbf_tks</code>
     */
    public static final SelectbfTks SELECTBF_TKS = new SelectbfTks();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SelectbfTksRecord> getRecordType() {
        return SelectbfTksRecord.class;
    }

    /**
     * The column <code>selectbf_tks.id</code>.
     */
    public final TableField<SelectbfTksRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>selectbf_tks.player_id</code>.
     */
    public final TableField<SelectbfTksRecord, Integer> PLAYER_ID = createField("player_id", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>selectbf_tks.victim_id</code>.
     */
    public final TableField<SelectbfTksRecord, Integer> VICTIM_ID = createField("victim_id", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>selectbf_tks.times_killed</code>.
     */
    public final TableField<SelectbfTksRecord, Integer> TIMES_KILLED = createField("times_killed", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("'0'", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * Create a <code>selectbf_tks</code> table reference
     */
    public SelectbfTks() {
        this("selectbf_tks", null);
    }

    /**
     * Create an aliased <code>selectbf_tks</code> table reference
     */
    public SelectbfTks(String alias) {
        this(alias, SELECTBF_TKS);
    }

    private SelectbfTks(String alias, Table<SelectbfTksRecord> aliased) {
        this(alias, aliased, null);
    }

    private SelectbfTks(String alias, Table<SelectbfTksRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<SelectbfTksRecord, Integer> getIdentity() {
        return Keys.IDENTITY_SELECTBF_TKS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SelectbfTksRecord> getPrimaryKey() {
        return Keys.PK_SELECTBF_TKS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SelectbfTksRecord>> getKeys() {
        return Arrays.<UniqueKey<SelectbfTksRecord>>asList(Keys.PK_SELECTBF_TKS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelectbfTks as(String alias) {
        return new SelectbfTks(alias, this);
    }

    /**
     * Rename this table
     */
    public SelectbfTks rename(String name) {
        return new SelectbfTks(name, null);
    }
}
