/**
 * This class is generated by jOOQ
 */
package io.github.bfvstats.jpa.tables;


import io.github.bfvstats.jpa.DefaultSchema;
import io.github.bfvstats.jpa.tables.records.SelectbfClanRankingRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SelectbfClanRanking extends TableImpl<SelectbfClanRankingRecord> {

    private static final long serialVersionUID = -1548990622;

    /**
     * The reference instance of <code>selectbf_clan_ranking</code>
     */
    public static final SelectbfClanRanking SELECTBF_CLAN_RANKING = new SelectbfClanRanking();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SelectbfClanRankingRecord> getRecordType() {
        return SelectbfClanRankingRecord.class;
    }

    /**
     * The column <code>selectbf_clan_ranking.ranks</code>.
     */
    public final TableField<SelectbfClanRankingRecord, Integer> RANKS = createField("ranks", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>selectbf_clan_ranking.score</code>.
     */
    public final TableField<SelectbfClanRankingRecord, Float> SCORE = createField("score", org.jooq.impl.SQLDataType.REAL.defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.REAL)), this, "");

    /**
     * The column <code>selectbf_clan_ranking.clanname</code>.
     */
    public final TableField<SelectbfClanRankingRecord, String> CLANNAME = createField("clanname", org.jooq.impl.SQLDataType.VARCHAR.length(100).defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>selectbf_clan_ranking.members</code>.
     */
    public final TableField<SelectbfClanRankingRecord, Integer> MEMBERS = createField("members", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>selectbf_clan_ranking.kills</code>.
     */
    public final TableField<SelectbfClanRankingRecord, Float> KILLS = createField("kills", org.jooq.impl.SQLDataType.REAL.defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.REAL)), this, "");

    /**
     * The column <code>selectbf_clan_ranking.deaths</code>.
     */
    public final TableField<SelectbfClanRankingRecord, Float> DEATHS = createField("deaths", org.jooq.impl.SQLDataType.REAL.defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.REAL)), this, "");

    /**
     * The column <code>selectbf_clan_ranking.kdrate</code>.
     */
    public final TableField<SelectbfClanRankingRecord, Float> KDRATE = createField("kdrate", org.jooq.impl.SQLDataType.REAL.defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.REAL)), this, "");

    /**
     * The column <code>selectbf_clan_ranking.tks</code>.
     */
    public final TableField<SelectbfClanRankingRecord, Float> TKS = createField("tks", org.jooq.impl.SQLDataType.REAL.defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.REAL)), this, "");

    /**
     * The column <code>selectbf_clan_ranking.captures</code>.
     */
    public final TableField<SelectbfClanRankingRecord, Float> CAPTURES = createField("captures", org.jooq.impl.SQLDataType.REAL.defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.REAL)), this, "");

    /**
     * The column <code>selectbf_clan_ranking.attacks</code>.
     */
    public final TableField<SelectbfClanRankingRecord, Float> ATTACKS = createField("attacks", org.jooq.impl.SQLDataType.REAL.defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.REAL)), this, "");

    /**
     * The column <code>selectbf_clan_ranking.defences</code>.
     */
    public final TableField<SelectbfClanRankingRecord, Float> DEFENCES = createField("defences", org.jooq.impl.SQLDataType.REAL.defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.REAL)), this, "");

    /**
     * The column <code>selectbf_clan_ranking.objectives</code>.
     */
    public final TableField<SelectbfClanRankingRecord, Float> OBJECTIVES = createField("objectives", org.jooq.impl.SQLDataType.REAL.defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.REAL)), this, "");

    /**
     * The column <code>selectbf_clan_ranking.objectivetks</code>.
     */
    public final TableField<SelectbfClanRankingRecord, Float> OBJECTIVETKS = createField("objectivetks", org.jooq.impl.SQLDataType.REAL.defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.REAL)), this, "");

    /**
     * The column <code>selectbf_clan_ranking.heals</code>.
     */
    public final TableField<SelectbfClanRankingRecord, Float> HEALS = createField("heals", org.jooq.impl.SQLDataType.REAL.defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.REAL)), this, "");

    /**
     * The column <code>selectbf_clan_ranking.selfheals</code>.
     */
    public final TableField<SelectbfClanRankingRecord, Float> SELFHEALS = createField("selfheals", org.jooq.impl.SQLDataType.REAL.defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.REAL)), this, "");

    /**
     * The column <code>selectbf_clan_ranking.repairs</code>.
     */
    public final TableField<SelectbfClanRankingRecord, Float> REPAIRS = createField("repairs", org.jooq.impl.SQLDataType.REAL.defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.REAL)), this, "");

    /**
     * The column <code>selectbf_clan_ranking.otherrepairs</code>.
     */
    public final TableField<SelectbfClanRankingRecord, Float> OTHERREPAIRS = createField("otherrepairs", org.jooq.impl.SQLDataType.REAL.defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.REAL)), this, "");

    /**
     * The column <code>selectbf_clan_ranking.rounds_played</code>.
     */
    public final TableField<SelectbfClanRankingRecord, Float> ROUNDS_PLAYED = createField("rounds_played", org.jooq.impl.SQLDataType.REAL.defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.REAL)), this, "");

    /**
     * Create a <code>selectbf_clan_ranking</code> table reference
     */
    public SelectbfClanRanking() {
        this("selectbf_clan_ranking", null);
    }

    /**
     * Create an aliased <code>selectbf_clan_ranking</code> table reference
     */
    public SelectbfClanRanking(String alias) {
        this(alias, SELECTBF_CLAN_RANKING);
    }

    private SelectbfClanRanking(String alias, Table<SelectbfClanRankingRecord> aliased) {
        this(alias, aliased, null);
    }

    private SelectbfClanRanking(String alias, Table<SelectbfClanRankingRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelectbfClanRanking as(String alias) {
        return new SelectbfClanRanking(alias, this);
    }

    /**
     * Rename this table
     */
    public SelectbfClanRanking rename(String name) {
        return new SelectbfClanRanking(name, null);
    }
}
