/**
 * This class is generated by jOOQ
 */
package io.github.bfvstats.jpa.tables;


import io.github.bfvstats.jpa.DefaultSchema;
import io.github.bfvstats.jpa.Keys;
import io.github.bfvstats.jpa.tables.records.SelectbfKitsRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SelectbfKits extends TableImpl<SelectbfKitsRecord> {

    private static final long serialVersionUID = 1846072573;

    /**
     * The reference instance of <code>selectbf_kits</code>
     */
    public static final SelectbfKits SELECTBF_KITS = new SelectbfKits();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SelectbfKitsRecord> getRecordType() {
        return SelectbfKitsRecord.class;
    }

    /**
     * The column <code>selectbf_kits.id</code>.
     */
    public final TableField<SelectbfKitsRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>selectbf_kits.player_id</code>.
     */
    public final TableField<SelectbfKitsRecord, Integer> PLAYER_ID = createField("player_id", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>selectbf_kits.kit</code>.
     */
    public final TableField<SelectbfKitsRecord, String> KIT = createField("kit", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>selectbf_kits.times_used</code>.
     */
    public final TableField<SelectbfKitsRecord, Integer> TIMES_USED = createField("times_used", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("'0'", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * Create a <code>selectbf_kits</code> table reference
     */
    public SelectbfKits() {
        this("selectbf_kits", null);
    }

    /**
     * Create an aliased <code>selectbf_kits</code> table reference
     */
    public SelectbfKits(String alias) {
        this(alias, SELECTBF_KITS);
    }

    private SelectbfKits(String alias, Table<SelectbfKitsRecord> aliased) {
        this(alias, aliased, null);
    }

    private SelectbfKits(String alias, Table<SelectbfKitsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<SelectbfKitsRecord, Integer> getIdentity() {
        return Keys.IDENTITY_SELECTBF_KITS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SelectbfKitsRecord> getPrimaryKey() {
        return Keys.PK_SELECTBF_KITS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SelectbfKitsRecord>> getKeys() {
        return Arrays.<UniqueKey<SelectbfKitsRecord>>asList(Keys.PK_SELECTBF_KITS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelectbfKits as(String alias) {
        return new SelectbfKits(alias, this);
    }

    /**
     * Rename this table
     */
    public SelectbfKits rename(String name) {
        return new SelectbfKits(name, null);
    }
}
