/**
 * This class is generated by jOOQ
 */
package io.github.bfvstats.jpa.tables;


import io.github.bfvstats.jpa.DefaultSchema;
import io.github.bfvstats.jpa.Keys;
import io.github.bfvstats.jpa.tables.records.SelectbfPlayersRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SelectbfPlayers extends TableImpl<SelectbfPlayersRecord> {

    private static final long serialVersionUID = 1970982329;

    /**
     * The reference instance of <code>selectbf_players</code>
     */
    public static final SelectbfPlayers SELECTBF_PLAYERS = new SelectbfPlayers();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SelectbfPlayersRecord> getRecordType() {
        return SelectbfPlayersRecord.class;
    }

    /**
     * The column <code>selectbf_players.id</code>.
     */
    public final TableField<SelectbfPlayersRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>selectbf_players.name</code>.
     */
    public final TableField<SelectbfPlayersRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(150).defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>selectbf_players.keyhash</code>.
     */
    public final TableField<SelectbfPlayersRecord, String> KEYHASH = createField("keyhash", org.jooq.impl.SQLDataType.VARCHAR.length(32).nullable(false).defaultValue(org.jooq.impl.DSL.field("''", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>selectbf_players.inserttime</code>.
     */
    public final TableField<SelectbfPlayersRecord, Timestamp> INSERTTIME = createField("inserttime", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>selectbf_players</code> table reference
     */
    public SelectbfPlayers() {
        this("selectbf_players", null);
    }

    /**
     * Create an aliased <code>selectbf_players</code> table reference
     */
    public SelectbfPlayers(String alias) {
        this(alias, SELECTBF_PLAYERS);
    }

    private SelectbfPlayers(String alias, Table<SelectbfPlayersRecord> aliased) {
        this(alias, aliased, null);
    }

    private SelectbfPlayers(String alias, Table<SelectbfPlayersRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<SelectbfPlayersRecord, Integer> getIdentity() {
        return Keys.IDENTITY_SELECTBF_PLAYERS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SelectbfPlayersRecord> getPrimaryKey() {
        return Keys.PK_SELECTBF_PLAYERS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SelectbfPlayersRecord>> getKeys() {
        return Arrays.<UniqueKey<SelectbfPlayersRecord>>asList(Keys.PK_SELECTBF_PLAYERS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelectbfPlayers as(String alias) {
        return new SelectbfPlayers(alias, this);
    }

    /**
     * Rename this table
     */
    public SelectbfPlayers rename(String name) {
        return new SelectbfPlayers(name, null);
    }
}
