/**
 * This class is generated by jOOQ
 */
package io.github.bfvstats.jpa.tables;


import io.github.bfvstats.jpa.DefaultSchema;
import io.github.bfvstats.jpa.Keys;
import io.github.bfvstats.jpa.tables.records.SelectbfAdminRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SelectbfAdmin extends TableImpl<SelectbfAdminRecord> {

    private static final long serialVersionUID = 1903604668;

    /**
     * The reference instance of <code>selectbf_admin</code>
     */
    public static final SelectbfAdmin SELECTBF_ADMIN = new SelectbfAdmin();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SelectbfAdminRecord> getRecordType() {
        return SelectbfAdminRecord.class;
    }

    /**
     * The column <code>selectbf_admin.id</code>.
     */
    public final TableField<SelectbfAdminRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>selectbf_admin.name</code>.
     */
    public final TableField<SelectbfAdminRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>selectbf_admin.value</code>.
     */
    public final TableField<SelectbfAdminRecord, String> VALUE = createField("value", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>selectbf_admin.inserttime</code>.
     */
    public final TableField<SelectbfAdminRecord, Timestamp> INSERTTIME = createField("inserttime", org.jooq.impl.SQLDataType.TIMESTAMP.defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>selectbf_admin</code> table reference
     */
    public SelectbfAdmin() {
        this("selectbf_admin", null);
    }

    /**
     * Create an aliased <code>selectbf_admin</code> table reference
     */
    public SelectbfAdmin(String alias) {
        this(alias, SELECTBF_ADMIN);
    }

    private SelectbfAdmin(String alias, Table<SelectbfAdminRecord> aliased) {
        this(alias, aliased, null);
    }

    private SelectbfAdmin(String alias, Table<SelectbfAdminRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SelectbfAdminRecord> getPrimaryKey() {
        return Keys.PK_SELECTBF_ADMIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SelectbfAdminRecord>> getKeys() {
        return Arrays.<UniqueKey<SelectbfAdminRecord>>asList(Keys.PK_SELECTBF_ADMIN);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelectbfAdmin as(String alias) {
        return new SelectbfAdmin(alias, this);
    }

    /**
     * Rename this table
     */
    public SelectbfAdmin rename(String name) {
        return new SelectbfAdmin(name, null);
    }
}
