/**
 * This class is generated by jOOQ
 */
package io.github.bfvstats.jpa.tables;


import io.github.bfvstats.jpa.DefaultSchema;
import io.github.bfvstats.jpa.Keys;
import io.github.bfvstats.jpa.tables.records.SelectbfCacheVehicletimeRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SelectbfCacheVehicletime extends TableImpl<SelectbfCacheVehicletimeRecord> {

    private static final long serialVersionUID = 834790063;

    /**
     * The reference instance of <code>selectbf_cache_vehicletime</code>
     */
    public static final SelectbfCacheVehicletime SELECTBF_CACHE_VEHICLETIME = new SelectbfCacheVehicletime();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SelectbfCacheVehicletimeRecord> getRecordType() {
        return SelectbfCacheVehicletimeRecord.class;
    }

    /**
     * The column <code>selectbf_cache_vehicletime.vehicle</code>.
     */
    public final TableField<SelectbfCacheVehicletimeRecord, String> VEHICLE = createField("vehicle", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false).defaultValue(org.jooq.impl.DSL.field("''", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>selectbf_cache_vehicletime.time</code>.
     */
    public final TableField<SelectbfCacheVehicletimeRecord, Float> TIME = createField("time", org.jooq.impl.SQLDataType.REAL.defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.REAL)), this, "");

    /**
     * The column <code>selectbf_cache_vehicletime.percentage_time</code>.
     */
    public final TableField<SelectbfCacheVehicletimeRecord, Float> PERCENTAGE_TIME = createField("percentage_time", org.jooq.impl.SQLDataType.REAL.defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.REAL)), this, "");

    /**
     * The column <code>selectbf_cache_vehicletime.times_used</code>.
     */
    public final TableField<SelectbfCacheVehicletimeRecord, Integer> TIMES_USED = createField("times_used", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>selectbf_cache_vehicletime.percentage_usage</code>.
     */
    public final TableField<SelectbfCacheVehicletimeRecord, Float> PERCENTAGE_USAGE = createField("percentage_usage", org.jooq.impl.SQLDataType.REAL.defaultValue(org.jooq.impl.DSL.field("NULL", org.jooq.impl.SQLDataType.REAL)), this, "");

    /**
     * Create a <code>selectbf_cache_vehicletime</code> table reference
     */
    public SelectbfCacheVehicletime() {
        this("selectbf_cache_vehicletime", null);
    }

    /**
     * Create an aliased <code>selectbf_cache_vehicletime</code> table reference
     */
    public SelectbfCacheVehicletime(String alias) {
        this(alias, SELECTBF_CACHE_VEHICLETIME);
    }

    private SelectbfCacheVehicletime(String alias, Table<SelectbfCacheVehicletimeRecord> aliased) {
        this(alias, aliased, null);
    }

    private SelectbfCacheVehicletime(String alias, Table<SelectbfCacheVehicletimeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SelectbfCacheVehicletimeRecord> getPrimaryKey() {
        return Keys.PK_SELECTBF_CACHE_VEHICLETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SelectbfCacheVehicletimeRecord>> getKeys() {
        return Arrays.<UniqueKey<SelectbfCacheVehicletimeRecord>>asList(Keys.PK_SELECTBF_CACHE_VEHICLETIME);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelectbfCacheVehicletime as(String alias) {
        return new SelectbfCacheVehicletime(alias, this);
    }

    /**
     * Rename this table
     */
    public SelectbfCacheVehicletime rename(String name) {
        return new SelectbfCacheVehicletime(name, null);
    }
}
