/*
 * This file is generated by jOOQ.
*/
package io.github.bfvstats.game.jooq.tables.records;


import io.github.bfvstats.game.jooq.tables.RoundPlayerRepair;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoundPlayerRepairRecord extends UpdatableRecordImpl<RoundPlayerRepairRecord> implements Record16<Integer, Integer, Integer, BigDecimal, BigDecimal, BigDecimal, Timestamp, Timestamp, Integer, Integer, String, Integer, BigDecimal, BigDecimal, BigDecimal, Integer> {

    private static final long serialVersionUID = 1609001782;

    /**
     * Setter for <code>round_player_repair.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>round_player_repair.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>round_player_repair.round_id</code>.
     */
    public void setRoundId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>round_player_repair.round_id</code>.
     */
    public Integer getRoundId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>round_player_repair.player_id</code>.
     */
    public void setPlayerId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>round_player_repair.player_id</code>.
     */
    public Integer getPlayerId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>round_player_repair.player_location_x</code>.
     */
    public void setPlayerLocationX(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>round_player_repair.player_location_x</code>.
     */
    public BigDecimal getPlayerLocationX() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>round_player_repair.player_location_y</code>.
     */
    public void setPlayerLocationY(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>round_player_repair.player_location_y</code>.
     */
    public BigDecimal getPlayerLocationY() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>round_player_repair.player_location_z</code>.
     */
    public void setPlayerLocationZ(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>round_player_repair.player_location_z</code>.
     */
    public BigDecimal getPlayerLocationZ() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>round_player_repair.start_time</code>.
     */
    public void setStartTime(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>round_player_repair.start_time</code>.
     */
    public Timestamp getStartTime() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>round_player_repair.end_time</code>.
     */
    public void setEndTime(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>round_player_repair.end_time</code>.
     */
    public Timestamp getEndTime() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>round_player_repair.duration_seconds</code>.
     */
    public void setDurationSeconds(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>round_player_repair.duration_seconds</code>.
     */
    public Integer getDurationSeconds() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>round_player_repair.start_repair_status</code>.
     */
    public void setStartRepairStatus(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>round_player_repair.start_repair_status</code>.
     */
    public Integer getStartRepairStatus() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>round_player_repair.vehicle_type</code>.
     */
    public void setVehicleType(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>round_player_repair.vehicle_type</code>.
     */
    public String getVehicleType() {
        return (String) get(10);
    }

    /**
     * Setter for <code>round_player_repair.vehicle_player_id</code>.
     */
    public void setVehiclePlayerId(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>round_player_repair.vehicle_player_id</code>.
     */
    public Integer getVehiclePlayerId() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>round_player_repair.end_player_location_x</code>.
     */
    public void setEndPlayerLocationX(BigDecimal value) {
        set(12, value);
    }

    /**
     * Getter for <code>round_player_repair.end_player_location_x</code>.
     */
    public BigDecimal getEndPlayerLocationX() {
        return (BigDecimal) get(12);
    }

    /**
     * Setter for <code>round_player_repair.end_player_location_y</code>.
     */
    public void setEndPlayerLocationY(BigDecimal value) {
        set(13, value);
    }

    /**
     * Getter for <code>round_player_repair.end_player_location_y</code>.
     */
    public BigDecimal getEndPlayerLocationY() {
        return (BigDecimal) get(13);
    }

    /**
     * Setter for <code>round_player_repair.end_player_location_z</code>.
     */
    public void setEndPlayerLocationZ(BigDecimal value) {
        set(14, value);
    }

    /**
     * Getter for <code>round_player_repair.end_player_location_z</code>.
     */
    public BigDecimal getEndPlayerLocationZ() {
        return (BigDecimal) get(14);
    }

    /**
     * Setter for <code>round_player_repair.end_repair_status</code>.
     */
    public void setEndRepairStatus(Integer value) {
        set(15, value);
    }

    /**
     * Getter for <code>round_player_repair.end_repair_status</code>.
     */
    public Integer getEndRepairStatus() {
        return (Integer) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<Integer, Integer, Integer, BigDecimal, BigDecimal, BigDecimal, Timestamp, Timestamp, Integer, Integer, String, Integer, BigDecimal, BigDecimal, BigDecimal, Integer> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<Integer, Integer, Integer, BigDecimal, BigDecimal, BigDecimal, Timestamp, Timestamp, Integer, Integer, String, Integer, BigDecimal, BigDecimal, BigDecimal, Integer> valuesRow() {
        return (Row16) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return RoundPlayerRepair.ROUND_PLAYER_REPAIR.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return RoundPlayerRepair.ROUND_PLAYER_REPAIR.ROUND_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return RoundPlayerRepair.ROUND_PLAYER_REPAIR.PLAYER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field4() {
        return RoundPlayerRepair.ROUND_PLAYER_REPAIR.PLAYER_LOCATION_X;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field5() {
        return RoundPlayerRepair.ROUND_PLAYER_REPAIR.PLAYER_LOCATION_Y;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field6() {
        return RoundPlayerRepair.ROUND_PLAYER_REPAIR.PLAYER_LOCATION_Z;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return RoundPlayerRepair.ROUND_PLAYER_REPAIR.START_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return RoundPlayerRepair.ROUND_PLAYER_REPAIR.END_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return RoundPlayerRepair.ROUND_PLAYER_REPAIR.DURATION_SECONDS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return RoundPlayerRepair.ROUND_PLAYER_REPAIR.START_REPAIR_STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return RoundPlayerRepair.ROUND_PLAYER_REPAIR.VEHICLE_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field12() {
        return RoundPlayerRepair.ROUND_PLAYER_REPAIR.VEHICLE_PLAYER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field13() {
        return RoundPlayerRepair.ROUND_PLAYER_REPAIR.END_PLAYER_LOCATION_X;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field14() {
        return RoundPlayerRepair.ROUND_PLAYER_REPAIR.END_PLAYER_LOCATION_Y;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field15() {
        return RoundPlayerRepair.ROUND_PLAYER_REPAIR.END_PLAYER_LOCATION_Z;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field16() {
        return RoundPlayerRepair.ROUND_PLAYER_REPAIR.END_REPAIR_STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getRoundId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getPlayerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value4() {
        return getPlayerLocationX();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value5() {
        return getPlayerLocationY();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value6() {
        return getPlayerLocationZ();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getStartTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getEndTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getDurationSeconds();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getStartRepairStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getVehicleType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value12() {
        return getVehiclePlayerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value13() {
        return getEndPlayerLocationX();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value14() {
        return getEndPlayerLocationY();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value15() {
        return getEndPlayerLocationZ();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value16() {
        return getEndRepairStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoundPlayerRepairRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoundPlayerRepairRecord value2(Integer value) {
        setRoundId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoundPlayerRepairRecord value3(Integer value) {
        setPlayerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoundPlayerRepairRecord value4(BigDecimal value) {
        setPlayerLocationX(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoundPlayerRepairRecord value5(BigDecimal value) {
        setPlayerLocationY(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoundPlayerRepairRecord value6(BigDecimal value) {
        setPlayerLocationZ(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoundPlayerRepairRecord value7(Timestamp value) {
        setStartTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoundPlayerRepairRecord value8(Timestamp value) {
        setEndTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoundPlayerRepairRecord value9(Integer value) {
        setDurationSeconds(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoundPlayerRepairRecord value10(Integer value) {
        setStartRepairStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoundPlayerRepairRecord value11(String value) {
        setVehicleType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoundPlayerRepairRecord value12(Integer value) {
        setVehiclePlayerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoundPlayerRepairRecord value13(BigDecimal value) {
        setEndPlayerLocationX(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoundPlayerRepairRecord value14(BigDecimal value) {
        setEndPlayerLocationY(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoundPlayerRepairRecord value15(BigDecimal value) {
        setEndPlayerLocationZ(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoundPlayerRepairRecord value16(Integer value) {
        setEndRepairStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoundPlayerRepairRecord values(Integer value1, Integer value2, Integer value3, BigDecimal value4, BigDecimal value5, BigDecimal value6, Timestamp value7, Timestamp value8, Integer value9, Integer value10, String value11, Integer value12, BigDecimal value13, BigDecimal value14, BigDecimal value15, Integer value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RoundPlayerRepairRecord
     */
    public RoundPlayerRepairRecord() {
        super(RoundPlayerRepair.ROUND_PLAYER_REPAIR);
    }

    /**
     * Create a detached, initialised RoundPlayerRepairRecord
     */
    public RoundPlayerRepairRecord(Integer id, Integer roundId, Integer playerId, BigDecimal playerLocationX, BigDecimal playerLocationY, BigDecimal playerLocationZ, Timestamp startTime, Timestamp endTime, Integer durationSeconds, Integer startRepairStatus, String vehicleType, Integer vehiclePlayerId, BigDecimal endPlayerLocationX, BigDecimal endPlayerLocationY, BigDecimal endPlayerLocationZ, Integer endRepairStatus) {
        super(RoundPlayerRepair.ROUND_PLAYER_REPAIR);

        set(0, id);
        set(1, roundId);
        set(2, playerId);
        set(3, playerLocationX);
        set(4, playerLocationY);
        set(5, playerLocationZ);
        set(6, startTime);
        set(7, endTime);
        set(8, durationSeconds);
        set(9, startRepairStatus);
        set(10, vehicleType);
        set(11, vehiclePlayerId);
        set(12, endPlayerLocationX);
        set(13, endPlayerLocationY);
        set(14, endPlayerLocationZ);
        set(15, endRepairStatus);
    }
}
