/*
 * This file is generated by jOOQ.
*/
package io.github.bfstats.dbstats.jooq.tables;


import io.github.bfstats.dbstats.jooq.DefaultSchema;
import io.github.bfstats.dbstats.jooq.Indexes;
import io.github.bfstats.dbstats.jooq.Keys;
import io.github.bfstats.dbstats.jooq.tables.records.GamePlayerRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GamePlayer extends TableImpl<GamePlayerRecord> {

    private static final long serialVersionUID = -436051766;

    /**
     * The reference instance of <code>game_player</code>
     */
    public static final GamePlayer GAME_PLAYER = new GamePlayer();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GamePlayerRecord> getRecordType() {
        return GamePlayerRecord.class;
    }

    /**
     * The column <code>game_player.id</code>.
     */
    public final TableField<GamePlayerRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>game_player.game_id</code>.
     */
    public final TableField<GamePlayerRecord, Integer> GAME_ID = createField("game_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>game_player.joined_round_id</code>.
     */
    public final TableField<GamePlayerRecord, Integer> JOINED_ROUND_ID = createField("joined_round_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>game_player.end_round_id</code>.
     */
    public final TableField<GamePlayerRecord, Integer> END_ROUND_ID = createField("end_round_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>game_player.player_id</code>.
     */
    public final TableField<GamePlayerRecord, Integer> PLAYER_ID = createField("player_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>game_player.start_time</code>.
     */
    public final TableField<GamePlayerRecord, Timestamp> START_TIME = createField("start_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>game_player.end_time</code>.
     */
    public final TableField<GamePlayerRecord, Timestamp> END_TIME = createField("end_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * Create a <code>game_player</code> table reference
     */
    public GamePlayer() {
        this(DSL.name("game_player"), null);
    }

    /**
     * Create an aliased <code>game_player</code> table reference
     */
    public GamePlayer(String alias) {
        this(DSL.name(alias), GAME_PLAYER);
    }

    /**
     * Create an aliased <code>game_player</code> table reference
     */
    public GamePlayer(Name alias) {
        this(alias, GAME_PLAYER);
    }

    private GamePlayer(Name alias, Table<GamePlayerRecord> aliased) {
        this(alias, aliased, null);
    }

    private GamePlayer(Name alias, Table<GamePlayerRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.GAME_PLAYER_END_ROUND_ID_IDX, Indexes.GAME_PLAYER_GAME_ID_IDX, Indexes.GAME_PLAYER_JOINED_ROUND_ID_IDX, Indexes.GAME_PLAYER_PLAYER_ID_IDX);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<GamePlayerRecord, Integer> getIdentity() {
        return Keys.IDENTITY_GAME_PLAYER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<GamePlayerRecord> getPrimaryKey() {
        return Keys.PK_GAME_PLAYER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<GamePlayerRecord>> getKeys() {
        return Arrays.<UniqueKey<GamePlayerRecord>>asList(Keys.PK_GAME_PLAYER);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<GamePlayerRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<GamePlayerRecord, ?>>asList(Keys.FK_GAME_PLAYER_GAME_1, Keys.FK_GAME_PLAYER_ROUND_2, Keys.FK_GAME_PLAYER_ROUND_1, Keys.FK_GAME_PLAYER_PLAYER_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GamePlayer as(String alias) {
        return new GamePlayer(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GamePlayer as(Name alias) {
        return new GamePlayer(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public GamePlayer rename(String name) {
        return new GamePlayer(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GamePlayer rename(Name name) {
        return new GamePlayer(name, null);
    }
}
