/*
 * This file is generated by jOOQ.
*/
package io.github.bfstats.dbstats.jooq.tables;


import io.github.bfstats.dbstats.jooq.DefaultSchema;
import io.github.bfstats.dbstats.jooq.tables.records.PlayerSummaryNoRankRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlayerSummaryNoRank extends TableImpl<PlayerSummaryNoRankRecord> {

    private static final long serialVersionUID = -630197074;

    /**
     * The reference instance of <code>player_summary_no_rank</code>
     */
    public static final PlayerSummaryNoRank PLAYER_SUMMARY_NO_RANK = new PlayerSummaryNoRank();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PlayerSummaryNoRankRecord> getRecordType() {
        return PlayerSummaryNoRankRecord.class;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<PlayerSummaryNoRankRecord, Object> ROUNDS_PLAYED = createField("rounds_played", org.jooq.impl.DefaultDataType.getDefaultDataType(""), this, "");

    /**
     * The column <code>player_summary_no_rank.player_name</code>.
     */
    public final TableField<PlayerSummaryNoRankRecord, String> PLAYER_NAME = createField("player_name", org.jooq.impl.SQLDataType.VARCHAR(150), this, "");

    /**
     * The column <code>player_summary_no_rank.player_id</code>.
     */
    public final TableField<PlayerSummaryNoRankRecord, Integer> PLAYER_ID = createField("player_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<PlayerSummaryNoRankRecord, Object> SCORE = createField("score", org.jooq.impl.DefaultDataType.getDefaultDataType(""), this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<PlayerSummaryNoRankRecord, Object> AVERAGE_SCORE = createField("average_score", org.jooq.impl.DefaultDataType.getDefaultDataType(""), this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<PlayerSummaryNoRankRecord, Object> KILLS = createField("kills", org.jooq.impl.DefaultDataType.getDefaultDataType(""), this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<PlayerSummaryNoRankRecord, Object> DEATHS = createField("deaths", org.jooq.impl.DefaultDataType.getDefaultDataType(""), this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<PlayerSummaryNoRankRecord, Object> KDRATE = createField("kdrate", org.jooq.impl.DefaultDataType.getDefaultDataType(""), this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<PlayerSummaryNoRankRecord, Object> TKS = createField("tks", org.jooq.impl.DefaultDataType.getDefaultDataType(""), this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<PlayerSummaryNoRankRecord, Object> CAPTURES = createField("captures", org.jooq.impl.DefaultDataType.getDefaultDataType(""), this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<PlayerSummaryNoRankRecord, Object> ATTACKS = createField("attacks", org.jooq.impl.DefaultDataType.getDefaultDataType(""), this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<PlayerSummaryNoRankRecord, Object> DEFENCES = createField("defences", org.jooq.impl.DefaultDataType.getDefaultDataType(""), this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<PlayerSummaryNoRankRecord, Object> GOLD_COUNT = createField("gold_count", org.jooq.impl.DefaultDataType.getDefaultDataType(""), this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<PlayerSummaryNoRankRecord, Object> SILVER_COUNT = createField("silver_count", org.jooq.impl.DefaultDataType.getDefaultDataType(""), this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<PlayerSummaryNoRankRecord, Object> BRONZE_COUNT = createField("bronze_count", org.jooq.impl.DefaultDataType.getDefaultDataType(""), this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<PlayerSummaryNoRankRecord, Object> HEALS_ALL_COUNT = createField("heals_all_count", org.jooq.impl.DefaultDataType.getDefaultDataType(""), this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<PlayerSummaryNoRankRecord, Object> HEALS_SELF_COUNT = createField("heals_self_count", org.jooq.impl.DefaultDataType.getDefaultDataType(""), this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<PlayerSummaryNoRankRecord, Object> HEALS_OTHERS_COUNT = createField("heals_others_count", org.jooq.impl.DefaultDataType.getDefaultDataType(""), this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<PlayerSummaryNoRankRecord, Object> REPAIRS_ALL_COUNT = createField("repairs_all_count", org.jooq.impl.DefaultDataType.getDefaultDataType(""), this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<PlayerSummaryNoRankRecord, Object> REPAIRS_SELF_COUNT = createField("repairs_self_count", org.jooq.impl.DefaultDataType.getDefaultDataType(""), this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<PlayerSummaryNoRankRecord, Object> REPAIRS_OTHERS_COUNT = createField("repairs_others_count", org.jooq.impl.DefaultDataType.getDefaultDataType(""), this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<PlayerSummaryNoRankRecord, Object> REPAIRS_UNMANNED_COUNT = createField("repairs_unmanned_count", org.jooq.impl.DefaultDataType.getDefaultDataType(""), this, "");

    /**
     * Create a <code>player_summary_no_rank</code> table reference
     */
    public PlayerSummaryNoRank() {
        this(DSL.name("player_summary_no_rank"), null);
    }

    /**
     * Create an aliased <code>player_summary_no_rank</code> table reference
     */
    public PlayerSummaryNoRank(String alias) {
        this(DSL.name(alias), PLAYER_SUMMARY_NO_RANK);
    }

    /**
     * Create an aliased <code>player_summary_no_rank</code> table reference
     */
    public PlayerSummaryNoRank(Name alias) {
        this(alias, PLAYER_SUMMARY_NO_RANK);
    }

    private PlayerSummaryNoRank(Name alias, Table<PlayerSummaryNoRankRecord> aliased) {
        this(alias, aliased, null);
    }

    private PlayerSummaryNoRank(Name alias, Table<PlayerSummaryNoRankRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PlayerSummaryNoRank as(String alias) {
        return new PlayerSummaryNoRank(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PlayerSummaryNoRank as(Name alias) {
        return new PlayerSummaryNoRank(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PlayerSummaryNoRank rename(String name) {
        return new PlayerSummaryNoRank(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PlayerSummaryNoRank rename(Name name) {
        return new PlayerSummaryNoRank(name, null);
    }
}
