/*
 * This file is generated by jOOQ.
*/
package io.github.bfstats.dbstats.jooq.tables;


import io.github.bfstats.dbstats.jooq.DefaultSchema;
import io.github.bfstats.dbstats.jooq.tables.records.PlayerTopStatsRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlayerTopStats extends TableImpl<PlayerTopStatsRecord> {

    private static final long serialVersionUID = -2095571430;

    /**
     * The reference instance of <code>player_top_stats</code>
     */
    public static final PlayerTopStats PLAYER_TOP_STATS = new PlayerTopStats();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PlayerTopStatsRecord> getRecordType() {
        return PlayerTopStatsRecord.class;
    }

    /**
     * The column <code>player_top_stats.player_id</code>.
     */
    public final TableField<PlayerTopStatsRecord, Integer> PLAYER_ID = createField("player_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<PlayerTopStatsRecord, Object> IS_MAX_POINTS = createField("is_max_points", org.jooq.impl.DefaultDataType.getDefaultDataType(""), this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<PlayerTopStatsRecord, Object> IS_MAX_SCORE = createField("is_max_score", org.jooq.impl.DefaultDataType.getDefaultDataType(""), this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<PlayerTopStatsRecord, Object> IS_MAX_GOLD_COUNT = createField("is_max_gold_count", org.jooq.impl.DefaultDataType.getDefaultDataType(""), this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<PlayerTopStatsRecord, Object> IS_MAX_SILVER_COUNT = createField("is_max_silver_count", org.jooq.impl.DefaultDataType.getDefaultDataType(""), this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<PlayerTopStatsRecord, Object> IS_MAX_BRONZE_COUNT = createField("is_max_bronze_count", org.jooq.impl.DefaultDataType.getDefaultDataType(""), this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<PlayerTopStatsRecord, Object> IS_MAX_HEALS_ALL_COUNT = createField("is_max_heals_all_count", org.jooq.impl.DefaultDataType.getDefaultDataType(""), this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<PlayerTopStatsRecord, Object> IS_MAX_REPAIRS_ALL_COUNT = createField("is_max_repairs_all_count", org.jooq.impl.DefaultDataType.getDefaultDataType(""), this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public final TableField<PlayerTopStatsRecord, Object> IS_MAX_CAPTURES = createField("is_max_captures", org.jooq.impl.DefaultDataType.getDefaultDataType(""), this, "");

    /**
     * Create a <code>player_top_stats</code> table reference
     */
    public PlayerTopStats() {
        this(DSL.name("player_top_stats"), null);
    }

    /**
     * Create an aliased <code>player_top_stats</code> table reference
     */
    public PlayerTopStats(String alias) {
        this(DSL.name(alias), PLAYER_TOP_STATS);
    }

    /**
     * Create an aliased <code>player_top_stats</code> table reference
     */
    public PlayerTopStats(Name alias) {
        this(alias, PLAYER_TOP_STATS);
    }

    private PlayerTopStats(Name alias, Table<PlayerTopStatsRecord> aliased) {
        this(alias, aliased, null);
    }

    private PlayerTopStats(Name alias, Table<PlayerTopStatsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PlayerTopStats as(String alias) {
        return new PlayerTopStats(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PlayerTopStats as(Name alias) {
        return new PlayerTopStats(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PlayerTopStats rename(String name) {
        return new PlayerTopStats(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PlayerTopStats rename(Name name) {
        return new PlayerTopStats(name, null);
    }
}
