/**
 * This class is generated by jOOQ
 */
package io.github.bfvstats.jpa.tables.records;


import io.github.bfvstats.jpa.tables.SelectbfModassignment;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SelectbfModassignmentRecord extends UpdatableRecordImpl<SelectbfModassignmentRecord> implements Record5<Integer, String, String, String, Timestamp> {

    private static final long serialVersionUID = 2006204883;

    /**
     * Setter for <code>selectbf_modassignment.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>selectbf_modassignment.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>selectbf_modassignment.item</code>.
     */
    public void setItem(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>selectbf_modassignment.item</code>.
     */
    public String getItem() {
        return (String) get(1);
    }

    /**
     * Setter for <code>selectbf_modassignment.mod</code>.
     */
    public void setMod(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>selectbf_modassignment.mod</code>.
     */
    public String getMod() {
        return (String) get(2);
    }

    /**
     * Setter for <code>selectbf_modassignment.type</code>.
     */
    public void setType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>selectbf_modassignment.type</code>.
     */
    public String getType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>selectbf_modassignment.inserttime</code>.
     */
    public void setInserttime(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>selectbf_modassignment.inserttime</code>.
     */
    public Timestamp getInserttime() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, String, String, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, String, String, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return SelectbfModassignment.SELECTBF_MODASSIGNMENT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return SelectbfModassignment.SELECTBF_MODASSIGNMENT.ITEM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return SelectbfModassignment.SELECTBF_MODASSIGNMENT.MOD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return SelectbfModassignment.SELECTBF_MODASSIGNMENT.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return SelectbfModassignment.SELECTBF_MODASSIGNMENT.INSERTTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getItem();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getMod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getInserttime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelectbfModassignmentRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelectbfModassignmentRecord value2(String value) {
        setItem(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelectbfModassignmentRecord value3(String value) {
        setMod(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelectbfModassignmentRecord value4(String value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelectbfModassignmentRecord value5(Timestamp value) {
        setInserttime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelectbfModassignmentRecord values(Integer value1, String value2, String value3, String value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SelectbfModassignmentRecord
     */
    public SelectbfModassignmentRecord() {
        super(SelectbfModassignment.SELECTBF_MODASSIGNMENT);
    }

    /**
     * Create a detached, initialised SelectbfModassignmentRecord
     */
    public SelectbfModassignmentRecord(Integer id, String item, String mod, String type, Timestamp inserttime) {
        super(SelectbfModassignment.SELECTBF_MODASSIGNMENT);

        set(0, id);
        set(1, item);
        set(2, mod);
        set(3, type);
        set(4, inserttime);
    }
}
