/**
 * This class is generated by jOOQ
 */
package io.github.bfvstats.jpa.tables.records;


import io.github.bfvstats.jpa.tables.SelectbfCategorymember;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SelectbfCategorymemberRecord extends TableRecordImpl<SelectbfCategorymemberRecord> implements Record2<String, Integer> {

    private static final long serialVersionUID = 1326673849;

    /**
     * Setter for <code>selectbf_categorymember.member</code>.
     */
    public void setMember(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>selectbf_categorymember.member</code>.
     */
    public String getMember() {
        return (String) get(0);
    }

    /**
     * Setter for <code>selectbf_categorymember.category</code>.
     */
    public void setCategory(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>selectbf_categorymember.category</code>.
     */
    public Integer getCategory() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return SelectbfCategorymember.SELECTBF_CATEGORYMEMBER.MEMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return SelectbfCategorymember.SELECTBF_CATEGORYMEMBER.CATEGORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getMember();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getCategory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelectbfCategorymemberRecord value1(String value) {
        setMember(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelectbfCategorymemberRecord value2(Integer value) {
        setCategory(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelectbfCategorymemberRecord values(String value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SelectbfCategorymemberRecord
     */
    public SelectbfCategorymemberRecord() {
        super(SelectbfCategorymember.SELECTBF_CATEGORYMEMBER);
    }

    /**
     * Create a detached, initialised SelectbfCategorymemberRecord
     */
    public SelectbfCategorymemberRecord(String member, Integer category) {
        super(SelectbfCategorymember.SELECTBF_CATEGORYMEMBER);

        set(0, member);
        set(1, category);
    }
}
