/**
 * This class is generated by jOOQ
 */
package io.github.bfvstats.jpa.tables.records;


import io.github.bfvstats.jpa.tables.SelectbfKillsWeapon;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SelectbfKillsWeaponRecord extends UpdatableRecordImpl<SelectbfKillsWeaponRecord> implements Record4<Integer, Integer, String, Integer> {

    private static final long serialVersionUID = -764576531;

    /**
     * Setter for <code>selectbf_kills_weapon.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>selectbf_kills_weapon.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>selectbf_kills_weapon.player_id</code>.
     */
    public void setPlayerId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>selectbf_kills_weapon.player_id</code>.
     */
    public Integer getPlayerId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>selectbf_kills_weapon.weapon</code>.
     */
    public void setWeapon(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>selectbf_kills_weapon.weapon</code>.
     */
    public String getWeapon() {
        return (String) get(2);
    }

    /**
     * Setter for <code>selectbf_kills_weapon.times_used</code>.
     */
    public void setTimesUsed(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>selectbf_kills_weapon.times_used</code>.
     */
    public Integer getTimesUsed() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, String, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, String, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return SelectbfKillsWeapon.SELECTBF_KILLS_WEAPON.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return SelectbfKillsWeapon.SELECTBF_KILLS_WEAPON.PLAYER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return SelectbfKillsWeapon.SELECTBF_KILLS_WEAPON.WEAPON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return SelectbfKillsWeapon.SELECTBF_KILLS_WEAPON.TIMES_USED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getPlayerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getWeapon();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getTimesUsed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelectbfKillsWeaponRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelectbfKillsWeaponRecord value2(Integer value) {
        setPlayerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelectbfKillsWeaponRecord value3(String value) {
        setWeapon(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelectbfKillsWeaponRecord value4(Integer value) {
        setTimesUsed(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelectbfKillsWeaponRecord values(Integer value1, Integer value2, String value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SelectbfKillsWeaponRecord
     */
    public SelectbfKillsWeaponRecord() {
        super(SelectbfKillsWeapon.SELECTBF_KILLS_WEAPON);
    }

    /**
     * Create a detached, initialised SelectbfKillsWeaponRecord
     */
    public SelectbfKillsWeaponRecord(Integer id, Integer playerId, String weapon, Integer timesUsed) {
        super(SelectbfKillsWeapon.SELECTBF_KILLS_WEAPON);

        set(0, id);
        set(1, playerId);
        set(2, weapon);
        set(3, timesUsed);
    }
}
