/**
 * This class is generated by jOOQ
 */
package io.github.bfvstats.jpa.tables.records;


import io.github.bfvstats.jpa.tables.SelectbfHeals;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SelectbfHealsRecord extends UpdatableRecordImpl<SelectbfHealsRecord> implements Record6<Integer, Integer, Integer, Integer, Float, Integer> {

    private static final long serialVersionUID = -1750655423;

    /**
     * Setter for <code>selectbf_heals.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>selectbf_heals.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>selectbf_heals.player_id</code>.
     */
    public void setPlayerId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>selectbf_heals.player_id</code>.
     */
    public Integer getPlayerId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>selectbf_heals.healed_player_id</code>.
     */
    public void setHealedPlayerId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>selectbf_heals.healed_player_id</code>.
     */
    public Integer getHealedPlayerId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>selectbf_heals.amount</code>.
     */
    public void setAmount(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>selectbf_heals.amount</code>.
     */
    public Integer getAmount() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>selectbf_heals.healtime</code>.
     */
    public void setHealtime(Float value) {
        set(4, value);
    }

    /**
     * Getter for <code>selectbf_heals.healtime</code>.
     */
    public Float getHealtime() {
        return (Float) get(4);
    }

    /**
     * Setter for <code>selectbf_heals.times_healed</code>.
     */
    public void setTimesHealed(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>selectbf_heals.times_healed</code>.
     */
    public Integer getTimesHealed() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Integer, Integer, Float, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Integer, Integer, Float, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return SelectbfHeals.SELECTBF_HEALS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return SelectbfHeals.SELECTBF_HEALS.PLAYER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return SelectbfHeals.SELECTBF_HEALS.HEALED_PLAYER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return SelectbfHeals.SELECTBF_HEALS.AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Float> field5() {
        return SelectbfHeals.SELECTBF_HEALS.HEALTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return SelectbfHeals.SELECTBF_HEALS.TIMES_HEALED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getPlayerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getHealedPlayerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float value5() {
        return getHealtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getTimesHealed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelectbfHealsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelectbfHealsRecord value2(Integer value) {
        setPlayerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelectbfHealsRecord value3(Integer value) {
        setHealedPlayerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelectbfHealsRecord value4(Integer value) {
        setAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelectbfHealsRecord value5(Float value) {
        setHealtime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelectbfHealsRecord value6(Integer value) {
        setTimesHealed(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelectbfHealsRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Float value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SelectbfHealsRecord
     */
    public SelectbfHealsRecord() {
        super(SelectbfHeals.SELECTBF_HEALS);
    }

    /**
     * Create a detached, initialised SelectbfHealsRecord
     */
    public SelectbfHealsRecord(Integer id, Integer playerId, Integer healedPlayerId, Integer amount, Float healtime, Integer timesHealed) {
        super(SelectbfHeals.SELECTBF_HEALS);

        set(0, id);
        set(1, playerId);
        set(2, healedPlayerId);
        set(3, amount);
        set(4, healtime);
        set(5, timesHealed);
    }
}
