/**
 * This class is generated by jOOQ
 */
package io.github.bfvstats.jpa.tables.records;


import io.github.bfvstats.jpa.tables.SelectbfTks;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SelectbfTksRecord extends UpdatableRecordImpl<SelectbfTksRecord> implements Record4<Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = -1447039202;

    /**
     * Setter for <code>selectbf_tks.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>selectbf_tks.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>selectbf_tks.player_id</code>.
     */
    public void setPlayerId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>selectbf_tks.player_id</code>.
     */
    public Integer getPlayerId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>selectbf_tks.victim_id</code>.
     */
    public void setVictimId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>selectbf_tks.victim_id</code>.
     */
    public Integer getVictimId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>selectbf_tks.times_killed</code>.
     */
    public void setTimesKilled(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>selectbf_tks.times_killed</code>.
     */
    public Integer getTimesKilled() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return SelectbfTks.SELECTBF_TKS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return SelectbfTks.SELECTBF_TKS.PLAYER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return SelectbfTks.SELECTBF_TKS.VICTIM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return SelectbfTks.SELECTBF_TKS.TIMES_KILLED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getPlayerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getVictimId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getTimesKilled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelectbfTksRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelectbfTksRecord value2(Integer value) {
        setPlayerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelectbfTksRecord value3(Integer value) {
        setVictimId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelectbfTksRecord value4(Integer value) {
        setTimesKilled(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelectbfTksRecord values(Integer value1, Integer value2, Integer value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SelectbfTksRecord
     */
    public SelectbfTksRecord() {
        super(SelectbfTks.SELECTBF_TKS);
    }

    /**
     * Create a detached, initialised SelectbfTksRecord
     */
    public SelectbfTksRecord(Integer id, Integer playerId, Integer victimId, Integer timesKilled) {
        super(SelectbfTks.SELECTBF_TKS);

        set(0, id);
        set(1, playerId);
        set(2, victimId);
        set(3, timesKilled);
    }
}
