/**
 * This class is generated by jOOQ
 */
package io.github.bfvstats.jpa.tables.records;


import io.github.bfvstats.jpa.tables.SelectbfCacheMapstats;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record17;
import org.jooq.Row17;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SelectbfCacheMapstatsRecord extends UpdatableRecordImpl<SelectbfCacheMapstatsRecord> implements Record17<String, Integer, Integer, Float, Float, Float, Float, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = -575095572;

    /**
     * Setter for <code>selectbf_cache_mapstats.map</code>.
     */
    public void setMap(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>selectbf_cache_mapstats.map</code>.
     */
    public String getMap() {
        return (String) get(0);
    }

    /**
     * Setter for <code>selectbf_cache_mapstats.wins_team1</code>.
     */
    public void setWinsTeam1(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>selectbf_cache_mapstats.wins_team1</code>.
     */
    public Integer getWinsTeam1() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>selectbf_cache_mapstats.wins_team2</code>.
     */
    public void setWinsTeam2(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>selectbf_cache_mapstats.wins_team2</code>.
     */
    public Integer getWinsTeam2() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>selectbf_cache_mapstats.win_team1_tickets_team1</code>.
     */
    public void setWinTeam1TicketsTeam1(Float value) {
        set(3, value);
    }

    /**
     * Getter for <code>selectbf_cache_mapstats.win_team1_tickets_team1</code>.
     */
    public Float getWinTeam1TicketsTeam1() {
        return (Float) get(3);
    }

    /**
     * Setter for <code>selectbf_cache_mapstats.win_team1_tickets_team2</code>.
     */
    public void setWinTeam1TicketsTeam2(Float value) {
        set(4, value);
    }

    /**
     * Getter for <code>selectbf_cache_mapstats.win_team1_tickets_team2</code>.
     */
    public Float getWinTeam1TicketsTeam2() {
        return (Float) get(4);
    }

    /**
     * Setter for <code>selectbf_cache_mapstats.win_team2_tickets_team1</code>.
     */
    public void setWinTeam2TicketsTeam1(Float value) {
        set(5, value);
    }

    /**
     * Getter for <code>selectbf_cache_mapstats.win_team2_tickets_team1</code>.
     */
    public Float getWinTeam2TicketsTeam1() {
        return (Float) get(5);
    }

    /**
     * Setter for <code>selectbf_cache_mapstats.win_team2_tickets_team2</code>.
     */
    public void setWinTeam2TicketsTeam2(Float value) {
        set(6, value);
    }

    /**
     * Getter for <code>selectbf_cache_mapstats.win_team2_tickets_team2</code>.
     */
    public Float getWinTeam2TicketsTeam2() {
        return (Float) get(6);
    }

    /**
     * Setter for <code>selectbf_cache_mapstats.score_team1</code>.
     */
    public void setScoreTeam1(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>selectbf_cache_mapstats.score_team1</code>.
     */
    public Integer getScoreTeam1() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>selectbf_cache_mapstats.score_team2</code>.
     */
    public void setScoreTeam2(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>selectbf_cache_mapstats.score_team2</code>.
     */
    public Integer getScoreTeam2() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>selectbf_cache_mapstats.kills_team1</code>.
     */
    public void setKillsTeam1(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>selectbf_cache_mapstats.kills_team1</code>.
     */
    public Integer getKillsTeam1() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>selectbf_cache_mapstats.kills_team2</code>.
     */
    public void setKillsTeam2(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>selectbf_cache_mapstats.kills_team2</code>.
     */
    public Integer getKillsTeam2() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>selectbf_cache_mapstats.deaths_team1</code>.
     */
    public void setDeathsTeam1(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>selectbf_cache_mapstats.deaths_team1</code>.
     */
    public Integer getDeathsTeam1() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>selectbf_cache_mapstats.deaths_team2</code>.
     */
    public void setDeathsTeam2(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>selectbf_cache_mapstats.deaths_team2</code>.
     */
    public Integer getDeathsTeam2() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>selectbf_cache_mapstats.attacks_team1</code>.
     */
    public void setAttacksTeam1(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>selectbf_cache_mapstats.attacks_team1</code>.
     */
    public Integer getAttacksTeam1() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>selectbf_cache_mapstats.attacks_team2</code>.
     */
    public void setAttacksTeam2(Integer value) {
        set(14, value);
    }

    /**
     * Getter for <code>selectbf_cache_mapstats.attacks_team2</code>.
     */
    public Integer getAttacksTeam2() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>selectbf_cache_mapstats.captures_team1</code>.
     */
    public void setCapturesTeam1(Integer value) {
        set(15, value);
    }

    /**
     * Getter for <code>selectbf_cache_mapstats.captures_team1</code>.
     */
    public Integer getCapturesTeam1() {
        return (Integer) get(15);
    }

    /**
     * Setter for <code>selectbf_cache_mapstats.captures_team2</code>.
     */
    public void setCapturesTeam2(Integer value) {
        set(16, value);
    }

    /**
     * Getter for <code>selectbf_cache_mapstats.captures_team2</code>.
     */
    public Integer getCapturesTeam2() {
        return (Integer) get(16);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record17 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row17<String, Integer, Integer, Float, Float, Float, Float, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row17) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row17<String, Integer, Integer, Float, Float, Float, Float, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer> valuesRow() {
        return (Row17) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return SelectbfCacheMapstats.SELECTBF_CACHE_MAPSTATS.MAP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return SelectbfCacheMapstats.SELECTBF_CACHE_MAPSTATS.WINS_TEAM1;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return SelectbfCacheMapstats.SELECTBF_CACHE_MAPSTATS.WINS_TEAM2;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Float> field4() {
        return SelectbfCacheMapstats.SELECTBF_CACHE_MAPSTATS.WIN_TEAM1_TICKETS_TEAM1;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Float> field5() {
        return SelectbfCacheMapstats.SELECTBF_CACHE_MAPSTATS.WIN_TEAM1_TICKETS_TEAM2;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Float> field6() {
        return SelectbfCacheMapstats.SELECTBF_CACHE_MAPSTATS.WIN_TEAM2_TICKETS_TEAM1;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Float> field7() {
        return SelectbfCacheMapstats.SELECTBF_CACHE_MAPSTATS.WIN_TEAM2_TICKETS_TEAM2;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return SelectbfCacheMapstats.SELECTBF_CACHE_MAPSTATS.SCORE_TEAM1;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return SelectbfCacheMapstats.SELECTBF_CACHE_MAPSTATS.SCORE_TEAM2;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return SelectbfCacheMapstats.SELECTBF_CACHE_MAPSTATS.KILLS_TEAM1;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return SelectbfCacheMapstats.SELECTBF_CACHE_MAPSTATS.KILLS_TEAM2;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field12() {
        return SelectbfCacheMapstats.SELECTBF_CACHE_MAPSTATS.DEATHS_TEAM1;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field13() {
        return SelectbfCacheMapstats.SELECTBF_CACHE_MAPSTATS.DEATHS_TEAM2;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field14() {
        return SelectbfCacheMapstats.SELECTBF_CACHE_MAPSTATS.ATTACKS_TEAM1;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field15() {
        return SelectbfCacheMapstats.SELECTBF_CACHE_MAPSTATS.ATTACKS_TEAM2;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field16() {
        return SelectbfCacheMapstats.SELECTBF_CACHE_MAPSTATS.CAPTURES_TEAM1;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field17() {
        return SelectbfCacheMapstats.SELECTBF_CACHE_MAPSTATS.CAPTURES_TEAM2;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getMap();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getWinsTeam1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getWinsTeam2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float value4() {
        return getWinTeam1TicketsTeam1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float value5() {
        return getWinTeam1TicketsTeam2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float value6() {
        return getWinTeam2TicketsTeam1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float value7() {
        return getWinTeam2TicketsTeam2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getScoreTeam1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getScoreTeam2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getKillsTeam1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getKillsTeam2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value12() {
        return getDeathsTeam1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value13() {
        return getDeathsTeam2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value14() {
        return getAttacksTeam1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value15() {
        return getAttacksTeam2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value16() {
        return getCapturesTeam1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value17() {
        return getCapturesTeam2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelectbfCacheMapstatsRecord value1(String value) {
        setMap(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelectbfCacheMapstatsRecord value2(Integer value) {
        setWinsTeam1(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelectbfCacheMapstatsRecord value3(Integer value) {
        setWinsTeam2(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelectbfCacheMapstatsRecord value4(Float value) {
        setWinTeam1TicketsTeam1(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelectbfCacheMapstatsRecord value5(Float value) {
        setWinTeam1TicketsTeam2(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelectbfCacheMapstatsRecord value6(Float value) {
        setWinTeam2TicketsTeam1(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelectbfCacheMapstatsRecord value7(Float value) {
        setWinTeam2TicketsTeam2(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelectbfCacheMapstatsRecord value8(Integer value) {
        setScoreTeam1(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelectbfCacheMapstatsRecord value9(Integer value) {
        setScoreTeam2(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelectbfCacheMapstatsRecord value10(Integer value) {
        setKillsTeam1(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelectbfCacheMapstatsRecord value11(Integer value) {
        setKillsTeam2(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelectbfCacheMapstatsRecord value12(Integer value) {
        setDeathsTeam1(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelectbfCacheMapstatsRecord value13(Integer value) {
        setDeathsTeam2(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelectbfCacheMapstatsRecord value14(Integer value) {
        setAttacksTeam1(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelectbfCacheMapstatsRecord value15(Integer value) {
        setAttacksTeam2(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelectbfCacheMapstatsRecord value16(Integer value) {
        setCapturesTeam1(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelectbfCacheMapstatsRecord value17(Integer value) {
        setCapturesTeam2(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelectbfCacheMapstatsRecord values(String value1, Integer value2, Integer value3, Float value4, Float value5, Float value6, Float value7, Integer value8, Integer value9, Integer value10, Integer value11, Integer value12, Integer value13, Integer value14, Integer value15, Integer value16, Integer value17) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SelectbfCacheMapstatsRecord
     */
    public SelectbfCacheMapstatsRecord() {
        super(SelectbfCacheMapstats.SELECTBF_CACHE_MAPSTATS);
    }

    /**
     * Create a detached, initialised SelectbfCacheMapstatsRecord
     */
    public SelectbfCacheMapstatsRecord(String map, Integer winsTeam1, Integer winsTeam2, Float winTeam1TicketsTeam1, Float winTeam1TicketsTeam2, Float winTeam2TicketsTeam1, Float winTeam2TicketsTeam2, Integer scoreTeam1, Integer scoreTeam2, Integer killsTeam1, Integer killsTeam2, Integer deathsTeam1, Integer deathsTeam2, Integer attacksTeam1, Integer attacksTeam2, Integer capturesTeam1, Integer capturesTeam2) {
        super(SelectbfCacheMapstats.SELECTBF_CACHE_MAPSTATS);

        set(0, map);
        set(1, winsTeam1);
        set(2, winsTeam2);
        set(3, winTeam1TicketsTeam1);
        set(4, winTeam1TicketsTeam2);
        set(5, winTeam2TicketsTeam1);
        set(6, winTeam2TicketsTeam2);
        set(7, scoreTeam1);
        set(8, scoreTeam2);
        set(9, killsTeam1);
        set(10, killsTeam2);
        set(11, deathsTeam1);
        set(12, deathsTeam2);
        set(13, attacksTeam1);
        set(14, attacksTeam2);
        set(15, capturesTeam1);
        set(16, capturesTeam2);
    }
}
