/**
 * This class is generated by jOOQ
 */
package io.github.bfvstats.jpa.tables.records;


import io.github.bfvstats.jpa.tables.SelectbfKits;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SelectbfKitsRecord extends UpdatableRecordImpl<SelectbfKitsRecord> implements Record4<Integer, Integer, String, Integer> {

    private static final long serialVersionUID = 244224583;

    /**
     * Setter for <code>selectbf_kits.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>selectbf_kits.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>selectbf_kits.player_id</code>.
     */
    public void setPlayerId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>selectbf_kits.player_id</code>.
     */
    public Integer getPlayerId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>selectbf_kits.kit</code>.
     */
    public void setKit(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>selectbf_kits.kit</code>.
     */
    public String getKit() {
        return (String) get(2);
    }

    /**
     * Setter for <code>selectbf_kits.times_used</code>.
     */
    public void setTimesUsed(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>selectbf_kits.times_used</code>.
     */
    public Integer getTimesUsed() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, String, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, String, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return SelectbfKits.SELECTBF_KITS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return SelectbfKits.SELECTBF_KITS.PLAYER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return SelectbfKits.SELECTBF_KITS.KIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return SelectbfKits.SELECTBF_KITS.TIMES_USED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getPlayerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getKit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getTimesUsed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelectbfKitsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelectbfKitsRecord value2(Integer value) {
        setPlayerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelectbfKitsRecord value3(String value) {
        setKit(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelectbfKitsRecord value4(Integer value) {
        setTimesUsed(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SelectbfKitsRecord values(Integer value1, Integer value2, String value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SelectbfKitsRecord
     */
    public SelectbfKitsRecord() {
        super(SelectbfKits.SELECTBF_KITS);
    }

    /**
     * Create a detached, initialised SelectbfKitsRecord
     */
    public SelectbfKitsRecord(Integer id, Integer playerId, String kit, Integer timesUsed) {
        super(SelectbfKits.SELECTBF_KITS);

        set(0, id);
        set(1, playerId);
        set(2, kit);
        set(3, timesUsed);
    }
}
