/**
 * This class is generated by jOOQ
 */
package io.github.bfvstats.jpa.tables.records;


import io.github.bfvstats.jpa.tables.SelectbfCacheRanking;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SelectbfCacheRankingRecord extends UpdatableRecordImpl<SelectbfCacheRankingRecord> {

    private static final long serialVersionUID = -2100933759;

    /**
     * Setter for <code>selectbf_cache_ranking.rank</code>.
     */
    public void setRank(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>selectbf_cache_ranking.rank</code>.
     */
    public Integer getRank() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>selectbf_cache_ranking.player_id</code>.
     */
    public void setPlayerId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>selectbf_cache_ranking.player_id</code>.
     */
    public Integer getPlayerId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>selectbf_cache_ranking.playername</code>.
     */
    public void setPlayername(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>selectbf_cache_ranking.playername</code>.
     */
    public String getPlayername() {
        return (String) get(2);
    }

    /**
     * Setter for <code>selectbf_cache_ranking.score</code>.
     */
    public void setScore(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>selectbf_cache_ranking.score</code>.
     */
    public Integer getScore() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>selectbf_cache_ranking.kills</code>.
     */
    public void setKills(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>selectbf_cache_ranking.kills</code>.
     */
    public Integer getKills() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>selectbf_cache_ranking.deaths</code>.
     */
    public void setDeaths(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>selectbf_cache_ranking.deaths</code>.
     */
    public Integer getDeaths() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>selectbf_cache_ranking.kdrate</code>.
     */
    public void setKdrate(Double value) {
        set(6, value);
    }

    /**
     * Getter for <code>selectbf_cache_ranking.kdrate</code>.
     */
    public Double getKdrate() {
        return (Double) get(6);
    }

    /**
     * Setter for <code>selectbf_cache_ranking.score_per_minute</code>.
     */
    public void setScorePerMinute(Double value) {
        set(7, value);
    }

    /**
     * Getter for <code>selectbf_cache_ranking.score_per_minute</code>.
     */
    public Double getScorePerMinute() {
        return (Double) get(7);
    }

    /**
     * Setter for <code>selectbf_cache_ranking.tks</code>.
     */
    public void setTks(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>selectbf_cache_ranking.tks</code>.
     */
    public Integer getTks() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>selectbf_cache_ranking.captures</code>.
     */
    public void setCaptures(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>selectbf_cache_ranking.captures</code>.
     */
    public Integer getCaptures() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>selectbf_cache_ranking.attacks</code>.
     */
    public void setAttacks(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>selectbf_cache_ranking.attacks</code>.
     */
    public Integer getAttacks() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>selectbf_cache_ranking.defences</code>.
     */
    public void setDefences(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>selectbf_cache_ranking.defences</code>.
     */
    public Integer getDefences() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>selectbf_cache_ranking.objectives</code>.
     */
    public void setObjectives(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>selectbf_cache_ranking.objectives</code>.
     */
    public Integer getObjectives() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>selectbf_cache_ranking.objectivetks</code>.
     */
    public void setObjectivetks(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>selectbf_cache_ranking.objectivetks</code>.
     */
    public Integer getObjectivetks() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>selectbf_cache_ranking.heals</code>.
     */
    public void setHeals(Integer value) {
        set(14, value);
    }

    /**
     * Getter for <code>selectbf_cache_ranking.heals</code>.
     */
    public Integer getHeals() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>selectbf_cache_ranking.selfheals</code>.
     */
    public void setSelfheals(Integer value) {
        set(15, value);
    }

    /**
     * Getter for <code>selectbf_cache_ranking.selfheals</code>.
     */
    public Integer getSelfheals() {
        return (Integer) get(15);
    }

    /**
     * Setter for <code>selectbf_cache_ranking.repairs</code>.
     */
    public void setRepairs(Byte value) {
        set(16, value);
    }

    /**
     * Getter for <code>selectbf_cache_ranking.repairs</code>.
     */
    public Byte getRepairs() {
        return (Byte) get(16);
    }

    /**
     * Setter for <code>selectbf_cache_ranking.otherrepairs</code>.
     */
    public void setOtherrepairs(Byte value) {
        set(17, value);
    }

    /**
     * Getter for <code>selectbf_cache_ranking.otherrepairs</code>.
     */
    public Byte getOtherrepairs() {
        return (Byte) get(17);
    }

    /**
     * Setter for <code>selectbf_cache_ranking.first</code>.
     */
    public void setFirst(Byte value) {
        set(18, value);
    }

    /**
     * Getter for <code>selectbf_cache_ranking.first</code>.
     */
    public Byte getFirst() {
        return (Byte) get(18);
    }

    /**
     * Setter for <code>selectbf_cache_ranking.second</code>.
     */
    public void setSecond(Byte value) {
        set(19, value);
    }

    /**
     * Getter for <code>selectbf_cache_ranking.second</code>.
     */
    public Byte getSecond() {
        return (Byte) get(19);
    }

    /**
     * Setter for <code>selectbf_cache_ranking.third</code>.
     */
    public void setThird(Byte value) {
        set(20, value);
    }

    /**
     * Getter for <code>selectbf_cache_ranking.third</code>.
     */
    public Byte getThird() {
        return (Byte) get(20);
    }

    /**
     * Setter for <code>selectbf_cache_ranking.playtime</code>.
     */
    public void setPlaytime(Double value) {
        set(21, value);
    }

    /**
     * Getter for <code>selectbf_cache_ranking.playtime</code>.
     */
    public Double getPlaytime() {
        return (Double) get(21);
    }

    /**
     * Setter for <code>selectbf_cache_ranking.rounds_played</code>.
     */
    public void setRoundsPlayed(Integer value) {
        set(22, value);
    }

    /**
     * Getter for <code>selectbf_cache_ranking.rounds_played</code>.
     */
    public Integer getRoundsPlayed() {
        return (Integer) get(22);
    }

    /**
     * Setter for <code>selectbf_cache_ranking.last_visit</code>.
     */
    public void setLastVisit(Timestamp value) {
        set(23, value);
    }

    /**
     * Getter for <code>selectbf_cache_ranking.last_visit</code>.
     */
    public Timestamp getLastVisit() {
        return (Timestamp) get(23);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SelectbfCacheRankingRecord
     */
    public SelectbfCacheRankingRecord() {
        super(SelectbfCacheRanking.SELECTBF_CACHE_RANKING);
    }

    /**
     * Create a detached, initialised SelectbfCacheRankingRecord
     */
    public SelectbfCacheRankingRecord(Integer rank, Integer playerId, String playername, Integer score, Integer kills, Integer deaths, Double kdrate, Double scorePerMinute, Integer tks, Integer captures, Integer attacks, Integer defences, Integer objectives, Integer objectivetks, Integer heals, Integer selfheals, Byte repairs, Byte otherrepairs, Byte first, Byte second, Byte third, Double playtime, Integer roundsPlayed, Timestamp lastVisit) {
        super(SelectbfCacheRanking.SELECTBF_CACHE_RANKING);

        set(0, rank);
        set(1, playerId);
        set(2, playername);
        set(3, score);
        set(4, kills);
        set(5, deaths);
        set(6, kdrate);
        set(7, scorePerMinute);
        set(8, tks);
        set(9, captures);
        set(10, attacks);
        set(11, defences);
        set(12, objectives);
        set(13, objectivetks);
        set(14, heals);
        set(15, selfheals);
        set(16, repairs);
        set(17, otherrepairs);
        set(18, first);
        set(19, second);
        set(20, third);
        set(21, playtime);
        set(22, roundsPlayed);
        set(23, lastVisit);
    }
}
