/**
 * This class is generated by jOOQ
 */
package io.github.bfvstats.jpa;


import io.github.bfvstats.jpa.tables.SelectbfAdmin;
import io.github.bfvstats.jpa.tables.SelectbfCacheChartypeusage;
import io.github.bfvstats.jpa.tables.SelectbfCacheMapstats;
import io.github.bfvstats.jpa.tables.SelectbfCacheRanking;
import io.github.bfvstats.jpa.tables.SelectbfCacheVehicletime;
import io.github.bfvstats.jpa.tables.SelectbfCacheWeaponkills;
import io.github.bfvstats.jpa.tables.SelectbfCategory;
import io.github.bfvstats.jpa.tables.SelectbfCategorymember;
import io.github.bfvstats.jpa.tables.SelectbfChatlog;
import io.github.bfvstats.jpa.tables.SelectbfClanRanking;
import io.github.bfvstats.jpa.tables.SelectbfClanTags;
import io.github.bfvstats.jpa.tables.SelectbfCleartext;
import io.github.bfvstats.jpa.tables.SelectbfDrives;
import io.github.bfvstats.jpa.tables.SelectbfGames;
import io.github.bfvstats.jpa.tables.SelectbfHeals;
import io.github.bfvstats.jpa.tables.SelectbfKillsPlayer;
import io.github.bfvstats.jpa.tables.SelectbfKillsWeapon;
import io.github.bfvstats.jpa.tables.SelectbfKits;
import io.github.bfvstats.jpa.tables.SelectbfModassignment;
import io.github.bfvstats.jpa.tables.SelectbfNicknames;
import io.github.bfvstats.jpa.tables.SelectbfParams;
import io.github.bfvstats.jpa.tables.SelectbfPlayers;
import io.github.bfvstats.jpa.tables.SelectbfPlayerstats;
import io.github.bfvstats.jpa.tables.SelectbfPlaytimes;
import io.github.bfvstats.jpa.tables.SelectbfRepairs;
import io.github.bfvstats.jpa.tables.SelectbfRounds;
import io.github.bfvstats.jpa.tables.SelectbfSelfkills;
import io.github.bfvstats.jpa.tables.SelectbfTks;
import io.github.bfvstats.jpa.tables.SqliteSequence;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = -799590265;

    /**
     * The reference instance of <code></code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>selectbf_admin</code>.
     */
    public final SelectbfAdmin SELECTBF_ADMIN = io.github.bfvstats.jpa.tables.SelectbfAdmin.SELECTBF_ADMIN;

    /**
     * The table <code>selectbf_cache_chartypeusage</code>.
     */
    public final SelectbfCacheChartypeusage SELECTBF_CACHE_CHARTYPEUSAGE = io.github.bfvstats.jpa.tables.SelectbfCacheChartypeusage.SELECTBF_CACHE_CHARTYPEUSAGE;

    /**
     * The table <code>selectbf_cache_mapstats</code>.
     */
    public final SelectbfCacheMapstats SELECTBF_CACHE_MAPSTATS = io.github.bfvstats.jpa.tables.SelectbfCacheMapstats.SELECTBF_CACHE_MAPSTATS;

    /**
     * The table <code>selectbf_cache_ranking</code>.
     */
    public final SelectbfCacheRanking SELECTBF_CACHE_RANKING = io.github.bfvstats.jpa.tables.SelectbfCacheRanking.SELECTBF_CACHE_RANKING;

    /**
     * The table <code>selectbf_cache_vehicletime</code>.
     */
    public final SelectbfCacheVehicletime SELECTBF_CACHE_VEHICLETIME = io.github.bfvstats.jpa.tables.SelectbfCacheVehicletime.SELECTBF_CACHE_VEHICLETIME;

    /**
     * The table <code>selectbf_cache_weaponkills</code>.
     */
    public final SelectbfCacheWeaponkills SELECTBF_CACHE_WEAPONKILLS = io.github.bfvstats.jpa.tables.SelectbfCacheWeaponkills.SELECTBF_CACHE_WEAPONKILLS;

    /**
     * The table <code>selectbf_category</code>.
     */
    public final SelectbfCategory SELECTBF_CATEGORY = io.github.bfvstats.jpa.tables.SelectbfCategory.SELECTBF_CATEGORY;

    /**
     * The table <code>selectbf_categorymember</code>.
     */
    public final SelectbfCategorymember SELECTBF_CATEGORYMEMBER = io.github.bfvstats.jpa.tables.SelectbfCategorymember.SELECTBF_CATEGORYMEMBER;

    /**
     * The table <code>selectbf_chatlog</code>.
     */
    public final SelectbfChatlog SELECTBF_CHATLOG = io.github.bfvstats.jpa.tables.SelectbfChatlog.SELECTBF_CHATLOG;

    /**
     * The table <code>selectbf_clan_ranking</code>.
     */
    public final SelectbfClanRanking SELECTBF_CLAN_RANKING = io.github.bfvstats.jpa.tables.SelectbfClanRanking.SELECTBF_CLAN_RANKING;

    /**
     * The table <code>selectbf_clan_tags</code>.
     */
    public final SelectbfClanTags SELECTBF_CLAN_TAGS = io.github.bfvstats.jpa.tables.SelectbfClanTags.SELECTBF_CLAN_TAGS;

    /**
     * The table <code>selectbf_cleartext</code>.
     */
    public final SelectbfCleartext SELECTBF_CLEARTEXT = io.github.bfvstats.jpa.tables.SelectbfCleartext.SELECTBF_CLEARTEXT;

    /**
     * The table <code>selectbf_drives</code>.
     */
    public final SelectbfDrives SELECTBF_DRIVES = io.github.bfvstats.jpa.tables.SelectbfDrives.SELECTBF_DRIVES;

    /**
     * The table <code>selectbf_games</code>.
     */
    public final SelectbfGames SELECTBF_GAMES = io.github.bfvstats.jpa.tables.SelectbfGames.SELECTBF_GAMES;

    /**
     * The table <code>selectbf_heals</code>.
     */
    public final SelectbfHeals SELECTBF_HEALS = io.github.bfvstats.jpa.tables.SelectbfHeals.SELECTBF_HEALS;

    /**
     * The table <code>selectbf_kills_player</code>.
     */
    public final SelectbfKillsPlayer SELECTBF_KILLS_PLAYER = io.github.bfvstats.jpa.tables.SelectbfKillsPlayer.SELECTBF_KILLS_PLAYER;

    /**
     * The table <code>selectbf_kills_weapon</code>.
     */
    public final SelectbfKillsWeapon SELECTBF_KILLS_WEAPON = io.github.bfvstats.jpa.tables.SelectbfKillsWeapon.SELECTBF_KILLS_WEAPON;

    /**
     * The table <code>selectbf_kits</code>.
     */
    public final SelectbfKits SELECTBF_KITS = io.github.bfvstats.jpa.tables.SelectbfKits.SELECTBF_KITS;

    /**
     * The table <code>selectbf_modassignment</code>.
     */
    public final SelectbfModassignment SELECTBF_MODASSIGNMENT = io.github.bfvstats.jpa.tables.SelectbfModassignment.SELECTBF_MODASSIGNMENT;

    /**
     * The table <code>selectbf_nicknames</code>.
     */
    public final SelectbfNicknames SELECTBF_NICKNAMES = io.github.bfvstats.jpa.tables.SelectbfNicknames.SELECTBF_NICKNAMES;

    /**
     * The table <code>selectbf_params</code>.
     */
    public final SelectbfParams SELECTBF_PARAMS = io.github.bfvstats.jpa.tables.SelectbfParams.SELECTBF_PARAMS;

    /**
     * The table <code>selectbf_players</code>.
     */
    public final SelectbfPlayers SELECTBF_PLAYERS = io.github.bfvstats.jpa.tables.SelectbfPlayers.SELECTBF_PLAYERS;

    /**
     * The table <code>selectbf_playerstats</code>.
     */
    public final SelectbfPlayerstats SELECTBF_PLAYERSTATS = io.github.bfvstats.jpa.tables.SelectbfPlayerstats.SELECTBF_PLAYERSTATS;

    /**
     * The table <code>selectbf_playtimes</code>.
     */
    public final SelectbfPlaytimes SELECTBF_PLAYTIMES = io.github.bfvstats.jpa.tables.SelectbfPlaytimes.SELECTBF_PLAYTIMES;

    /**
     * The table <code>selectbf_repairs</code>.
     */
    public final SelectbfRepairs SELECTBF_REPAIRS = io.github.bfvstats.jpa.tables.SelectbfRepairs.SELECTBF_REPAIRS;

    /**
     * The table <code>selectbf_rounds</code>.
     */
    public final SelectbfRounds SELECTBF_ROUNDS = io.github.bfvstats.jpa.tables.SelectbfRounds.SELECTBF_ROUNDS;

    /**
     * The table <code>selectbf_selfkills</code>.
     */
    public final SelectbfSelfkills SELECTBF_SELFKILLS = io.github.bfvstats.jpa.tables.SelectbfSelfkills.SELECTBF_SELFKILLS;

    /**
     * The table <code>selectbf_tks</code>.
     */
    public final SelectbfTks SELECTBF_TKS = io.github.bfvstats.jpa.tables.SelectbfTks.SELECTBF_TKS;

    /**
     * The table <code>sqlite_sequence</code>.
     */
    public final SqliteSequence SQLITE_SEQUENCE = io.github.bfvstats.jpa.tables.SqliteSequence.SQLITE_SEQUENCE;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            SelectbfAdmin.SELECTBF_ADMIN,
            SelectbfCacheChartypeusage.SELECTBF_CACHE_CHARTYPEUSAGE,
            SelectbfCacheMapstats.SELECTBF_CACHE_MAPSTATS,
            SelectbfCacheRanking.SELECTBF_CACHE_RANKING,
            SelectbfCacheVehicletime.SELECTBF_CACHE_VEHICLETIME,
            SelectbfCacheWeaponkills.SELECTBF_CACHE_WEAPONKILLS,
            SelectbfCategory.SELECTBF_CATEGORY,
            SelectbfCategorymember.SELECTBF_CATEGORYMEMBER,
            SelectbfChatlog.SELECTBF_CHATLOG,
            SelectbfClanRanking.SELECTBF_CLAN_RANKING,
            SelectbfClanTags.SELECTBF_CLAN_TAGS,
            SelectbfCleartext.SELECTBF_CLEARTEXT,
            SelectbfDrives.SELECTBF_DRIVES,
            SelectbfGames.SELECTBF_GAMES,
            SelectbfHeals.SELECTBF_HEALS,
            SelectbfKillsPlayer.SELECTBF_KILLS_PLAYER,
            SelectbfKillsWeapon.SELECTBF_KILLS_WEAPON,
            SelectbfKits.SELECTBF_KITS,
            SelectbfModassignment.SELECTBF_MODASSIGNMENT,
            SelectbfNicknames.SELECTBF_NICKNAMES,
            SelectbfParams.SELECTBF_PARAMS,
            SelectbfPlayers.SELECTBF_PLAYERS,
            SelectbfPlayerstats.SELECTBF_PLAYERSTATS,
            SelectbfPlaytimes.SELECTBF_PLAYTIMES,
            SelectbfRepairs.SELECTBF_REPAIRS,
            SelectbfRounds.SELECTBF_ROUNDS,
            SelectbfSelfkills.SELECTBF_SELFKILLS,
            SelectbfTks.SELECTBF_TKS,
            SqliteSequence.SQLITE_SEQUENCE);
    }
}
