/**
 * This class is generated by jOOQ
 */
package io.github.bfvstats.jooq.tables.records;


import io.github.bfvstats.jooq.tables.RoundPlayerScoreEvent;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoundPlayerScoreEventRecord extends UpdatableRecordImpl<RoundPlayerScoreEventRecord> implements Record10<Integer, Integer, Integer, Float, Float, Float, Timestamp, String, Integer, String> {

    private static final long serialVersionUID = -876388801;

    /**
     * Setter for <code>round_player_score_event.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>round_player_score_event.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>round_player_score_event.round_id</code>.
     */
    public void setRoundId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>round_player_score_event.round_id</code>.
     */
    public Integer getRoundId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>round_player_score_event.player_id</code>.
     */
    public void setPlayerId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>round_player_score_event.player_id</code>.
     */
    public Integer getPlayerId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>round_player_score_event.player_location_x</code>.
     */
    public void setPlayerLocationX(Float value) {
        set(3, value);
    }

    /**
     * Getter for <code>round_player_score_event.player_location_x</code>.
     */
    public Float getPlayerLocationX() {
        return (Float) get(3);
    }

    /**
     * Setter for <code>round_player_score_event.player_location_y</code>.
     */
    public void setPlayerLocationY(Float value) {
        set(4, value);
    }

    /**
     * Getter for <code>round_player_score_event.player_location_y</code>.
     */
    public Float getPlayerLocationY() {
        return (Float) get(4);
    }

    /**
     * Setter for <code>round_player_score_event.player_location_z</code>.
     */
    public void setPlayerLocationZ(Float value) {
        set(5, value);
    }

    /**
     * Getter for <code>round_player_score_event.player_location_z</code>.
     */
    public Float getPlayerLocationZ() {
        return (Float) get(5);
    }

    /**
     * Setter for <code>round_player_score_event.event_time</code>.
     */
    public void setEventTime(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>round_player_score_event.event_time</code>.
     */
    public Timestamp getEventTime() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>round_player_score_event.score_type</code>.
     */
    public void setScoreType(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>round_player_score_event.score_type</code>.
     */
    public String getScoreType() {
        return (String) get(7);
    }

    /**
     * Setter for <code>round_player_score_event.victim_id</code>.
     */
    public void setVictimId(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>round_player_score_event.victim_id</code>.
     */
    public Integer getVictimId() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>round_player_score_event.weapon</code>.
     */
    public void setWeapon(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>round_player_score_event.weapon</code>.
     */
    public String getWeapon() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, Integer, Integer, Float, Float, Float, Timestamp, String, Integer, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, Integer, Integer, Float, Float, Float, Timestamp, String, Integer, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return RoundPlayerScoreEvent.ROUND_PLAYER_SCORE_EVENT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return RoundPlayerScoreEvent.ROUND_PLAYER_SCORE_EVENT.ROUND_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return RoundPlayerScoreEvent.ROUND_PLAYER_SCORE_EVENT.PLAYER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Float> field4() {
        return RoundPlayerScoreEvent.ROUND_PLAYER_SCORE_EVENT.PLAYER_LOCATION_X;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Float> field5() {
        return RoundPlayerScoreEvent.ROUND_PLAYER_SCORE_EVENT.PLAYER_LOCATION_Y;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Float> field6() {
        return RoundPlayerScoreEvent.ROUND_PLAYER_SCORE_EVENT.PLAYER_LOCATION_Z;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return RoundPlayerScoreEvent.ROUND_PLAYER_SCORE_EVENT.EVENT_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return RoundPlayerScoreEvent.ROUND_PLAYER_SCORE_EVENT.SCORE_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return RoundPlayerScoreEvent.ROUND_PLAYER_SCORE_EVENT.VICTIM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return RoundPlayerScoreEvent.ROUND_PLAYER_SCORE_EVENT.WEAPON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getRoundId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getPlayerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float value4() {
        return getPlayerLocationX();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float value5() {
        return getPlayerLocationY();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float value6() {
        return getPlayerLocationZ();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getEventTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getScoreType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getVictimId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getWeapon();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoundPlayerScoreEventRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoundPlayerScoreEventRecord value2(Integer value) {
        setRoundId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoundPlayerScoreEventRecord value3(Integer value) {
        setPlayerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoundPlayerScoreEventRecord value4(Float value) {
        setPlayerLocationX(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoundPlayerScoreEventRecord value5(Float value) {
        setPlayerLocationY(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoundPlayerScoreEventRecord value6(Float value) {
        setPlayerLocationZ(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoundPlayerScoreEventRecord value7(Timestamp value) {
        setEventTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoundPlayerScoreEventRecord value8(String value) {
        setScoreType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoundPlayerScoreEventRecord value9(Integer value) {
        setVictimId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoundPlayerScoreEventRecord value10(String value) {
        setWeapon(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoundPlayerScoreEventRecord values(Integer value1, Integer value2, Integer value3, Float value4, Float value5, Float value6, Timestamp value7, String value8, Integer value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RoundPlayerScoreEventRecord
     */
    public RoundPlayerScoreEventRecord() {
        super(RoundPlayerScoreEvent.ROUND_PLAYER_SCORE_EVENT);
    }

    /**
     * Create a detached, initialised RoundPlayerScoreEventRecord
     */
    public RoundPlayerScoreEventRecord(Integer id, Integer roundId, Integer playerId, Float playerLocationX, Float playerLocationY, Float playerLocationZ, Timestamp eventTime, String scoreType, Integer victimId, String weapon) {
        super(RoundPlayerScoreEvent.ROUND_PLAYER_SCORE_EVENT);

        set(0, id);
        set(1, roundId);
        set(2, playerId);
        set(3, playerLocationX);
        set(4, playerLocationY);
        set(5, playerLocationZ);
        set(6, eventTime);
        set(7, scoreType);
        set(8, victimId);
        set(9, weapon);
    }
}
