/*
 * This file is generated by jOOQ.
*/
package io.github.bfvstats.game.jooq.tables;


import io.github.bfvstats.game.jooq.DefaultSchema;
import io.github.bfvstats.game.jooq.Indexes;
import io.github.bfvstats.game.jooq.Keys;
import io.github.bfvstats.game.jooq.tables.records.RoundPlayerRepairRecord;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoundPlayerRepair extends TableImpl<RoundPlayerRepairRecord> {

    private static final long serialVersionUID = -1074566067;

    /**
     * The reference instance of <code>round_player_repair</code>
     */
    public static final RoundPlayerRepair ROUND_PLAYER_REPAIR = new RoundPlayerRepair();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RoundPlayerRepairRecord> getRecordType() {
        return RoundPlayerRepairRecord.class;
    }

    /**
     * The column <code>round_player_repair.id</code>.
     */
    public final TableField<RoundPlayerRepairRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>round_player_repair.round_id</code>.
     */
    public final TableField<RoundPlayerRepairRecord, Integer> ROUND_ID = createField("round_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>round_player_repair.player_id</code>.
     */
    public final TableField<RoundPlayerRepairRecord, Integer> PLAYER_ID = createField("player_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>round_player_repair.player_location_x</code>.
     */
    public final TableField<RoundPlayerRepairRecord, BigDecimal> PLAYER_LOCATION_X = createField("player_location_x", org.jooq.impl.SQLDataType.NUMERIC(4, 4).nullable(false), this, "");

    /**
     * The column <code>round_player_repair.player_location_y</code>.
     */
    public final TableField<RoundPlayerRepairRecord, BigDecimal> PLAYER_LOCATION_Y = createField("player_location_y", org.jooq.impl.SQLDataType.NUMERIC(4, 4).nullable(false), this, "");

    /**
     * The column <code>round_player_repair.player_location_z</code>.
     */
    public final TableField<RoundPlayerRepairRecord, BigDecimal> PLAYER_LOCATION_Z = createField("player_location_z", org.jooq.impl.SQLDataType.NUMERIC(4, 4).nullable(false), this, "");

    /**
     * The column <code>round_player_repair.start_time</code>.
     */
    public final TableField<RoundPlayerRepairRecord, Timestamp> START_TIME = createField("start_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>round_player_repair.end_time</code>.
     */
    public final TableField<RoundPlayerRepairRecord, Timestamp> END_TIME = createField("end_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>round_player_repair.duration_seconds</code>.
     */
    public final TableField<RoundPlayerRepairRecord, Integer> DURATION_SECONDS = createField("duration_seconds", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>round_player_repair.start_repair_status</code>.
     */
    public final TableField<RoundPlayerRepairRecord, Integer> START_REPAIR_STATUS = createField("start_repair_status", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>round_player_repair.vehicle_type</code>.
     */
    public final TableField<RoundPlayerRepairRecord, String> VEHICLE_TYPE = createField("vehicle_type", org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>round_player_repair.vehicle_player_id</code>.
     */
    public final TableField<RoundPlayerRepairRecord, Integer> VEHICLE_PLAYER_ID = createField("vehicle_player_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>round_player_repair.end_player_location_x</code>.
     */
    public final TableField<RoundPlayerRepairRecord, BigDecimal> END_PLAYER_LOCATION_X = createField("end_player_location_x", org.jooq.impl.SQLDataType.NUMERIC(4, 4), this, "");

    /**
     * The column <code>round_player_repair.end_player_location_y</code>.
     */
    public final TableField<RoundPlayerRepairRecord, BigDecimal> END_PLAYER_LOCATION_Y = createField("end_player_location_y", org.jooq.impl.SQLDataType.NUMERIC(4, 4), this, "");

    /**
     * The column <code>round_player_repair.end_player_location_z</code>.
     */
    public final TableField<RoundPlayerRepairRecord, BigDecimal> END_PLAYER_LOCATION_Z = createField("end_player_location_z", org.jooq.impl.SQLDataType.NUMERIC(4, 4), this, "");

    /**
     * The column <code>round_player_repair.end_repair_status</code>.
     */
    public final TableField<RoundPlayerRepairRecord, Integer> END_REPAIR_STATUS = createField("end_repair_status", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>round_player_repair</code> table reference
     */
    public RoundPlayerRepair() {
        this(DSL.name("round_player_repair"), null);
    }

    /**
     * Create an aliased <code>round_player_repair</code> table reference
     */
    public RoundPlayerRepair(String alias) {
        this(DSL.name(alias), ROUND_PLAYER_REPAIR);
    }

    /**
     * Create an aliased <code>round_player_repair</code> table reference
     */
    public RoundPlayerRepair(Name alias) {
        this(alias, ROUND_PLAYER_REPAIR);
    }

    private RoundPlayerRepair(Name alias, Table<RoundPlayerRepairRecord> aliased) {
        this(alias, aliased, null);
    }

    private RoundPlayerRepair(Name alias, Table<RoundPlayerRepairRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ROUND_PLAYER_REPAIR_PLAYER_ID_IDX, Indexes.ROUND_PLAYER_REPAIR_ROUND_ID_IDX, Indexes.ROUND_PLAYER_REPAIR_VEHICLE_PLAYER_ID_IDX);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<RoundPlayerRepairRecord, Integer> getIdentity() {
        return Keys.IDENTITY_ROUND_PLAYER_REPAIR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RoundPlayerRepairRecord> getPrimaryKey() {
        return Keys.PK_ROUND_PLAYER_REPAIR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RoundPlayerRepairRecord>> getKeys() {
        return Arrays.<UniqueKey<RoundPlayerRepairRecord>>asList(Keys.PK_ROUND_PLAYER_REPAIR);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<RoundPlayerRepairRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<RoundPlayerRepairRecord, ?>>asList(Keys.FK_ROUND_PLAYER_REPAIR_ROUND_1, Keys.FK_ROUND_PLAYER_REPAIR_PLAYER_2, Keys.FK_ROUND_PLAYER_REPAIR_PLAYER_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoundPlayerRepair as(String alias) {
        return new RoundPlayerRepair(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoundPlayerRepair as(Name alias) {
        return new RoundPlayerRepair(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RoundPlayerRepair rename(String name) {
        return new RoundPlayerRepair(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RoundPlayerRepair rename(Name name) {
        return new RoundPlayerRepair(name, null);
    }
}
