/*
 * This file is generated by jOOQ.
*/
package io.github.bfstats.dbstats.jooq;


import io.github.bfstats.dbstats.jooq.tables.Game;
import io.github.bfstats.dbstats.jooq.tables.GamePlayer;
import io.github.bfstats.dbstats.jooq.tables.Player;
import io.github.bfstats.dbstats.jooq.tables.PlayerNickname;
import io.github.bfstats.dbstats.jooq.tables.PlayerPoints;
import io.github.bfstats.dbstats.jooq.tables.PlayerRank;
import io.github.bfstats.dbstats.jooq.tables.PlayerSummary;
import io.github.bfstats.dbstats.jooq.tables.PlayerSummaryNoRank;
import io.github.bfstats.dbstats.jooq.tables.PlayerTopStats;
import io.github.bfstats.dbstats.jooq.tables.Round;
import io.github.bfstats.dbstats.jooq.tables.RoundChatLog;
import io.github.bfstats.dbstats.jooq.tables.RoundEndStats;
import io.github.bfstats.dbstats.jooq.tables.RoundEndStatsPlayer;
import io.github.bfstats.dbstats.jooq.tables.RoundPlayerDeath;
import io.github.bfstats.dbstats.jooq.tables.RoundPlayerDeployObject;
import io.github.bfstats.dbstats.jooq.tables.RoundPlayerMedpack;
import io.github.bfstats.dbstats.jooq.tables.RoundPlayerPickupKit;
import io.github.bfstats.dbstats.jooq.tables.RoundPlayerRepair;
import io.github.bfstats.dbstats.jooq.tables.RoundPlayerScoreEvent;
import io.github.bfstats.dbstats.jooq.tables.RoundPlayerTeam;
import io.github.bfstats.dbstats.jooq.tables.RoundPlayerVehicle;
import io.github.bfstats.dbstats.jooq.tables.Server;
import io.github.bfstats.dbstats.jooq.tables.Topid;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>game</code>.
     */
    public static final Game GAME = io.github.bfstats.dbstats.jooq.tables.Game.GAME;

    /**
     * The table <code>game_player</code>.
     */
    public static final GamePlayer GAME_PLAYER = io.github.bfstats.dbstats.jooq.tables.GamePlayer.GAME_PLAYER;

    /**
     * The table <code>player</code>.
     */
    public static final Player PLAYER = io.github.bfstats.dbstats.jooq.tables.Player.PLAYER;

    /**
     * The table <code>player_nickname</code>.
     */
    public static final PlayerNickname PLAYER_NICKNAME = io.github.bfstats.dbstats.jooq.tables.PlayerNickname.PLAYER_NICKNAME;

    /**
     * The table <code>player_points</code>.
     */
    public static final PlayerPoints PLAYER_POINTS = io.github.bfstats.dbstats.jooq.tables.PlayerPoints.PLAYER_POINTS;

    /**
     * The table <code>player_rank</code>.
     */
    public static final PlayerRank PLAYER_RANK = io.github.bfstats.dbstats.jooq.tables.PlayerRank.PLAYER_RANK;

    /**
     * The table <code>player_summary</code>.
     */
    public static final PlayerSummary PLAYER_SUMMARY = io.github.bfstats.dbstats.jooq.tables.PlayerSummary.PLAYER_SUMMARY;

    /**
     * The table <code>player_summary_no_rank</code>.
     */
    public static final PlayerSummaryNoRank PLAYER_SUMMARY_NO_RANK = io.github.bfstats.dbstats.jooq.tables.PlayerSummaryNoRank.PLAYER_SUMMARY_NO_RANK;

    /**
     * The table <code>player_top_stats</code>.
     */
    public static final PlayerTopStats PLAYER_TOP_STATS = io.github.bfstats.dbstats.jooq.tables.PlayerTopStats.PLAYER_TOP_STATS;

    /**
     * The table <code>round</code>.
     */
    public static final Round ROUND = io.github.bfstats.dbstats.jooq.tables.Round.ROUND;

    /**
     * The table <code>round_chat_log</code>.
     */
    public static final RoundChatLog ROUND_CHAT_LOG = io.github.bfstats.dbstats.jooq.tables.RoundChatLog.ROUND_CHAT_LOG;

    /**
     * The table <code>round_end_stats</code>.
     */
    public static final RoundEndStats ROUND_END_STATS = io.github.bfstats.dbstats.jooq.tables.RoundEndStats.ROUND_END_STATS;

    /**
     * The table <code>round_end_stats_player</code>.
     */
    public static final RoundEndStatsPlayer ROUND_END_STATS_PLAYER = io.github.bfstats.dbstats.jooq.tables.RoundEndStatsPlayer.ROUND_END_STATS_PLAYER;

    /**
     * The table <code>round_player_death</code>.
     */
    public static final RoundPlayerDeath ROUND_PLAYER_DEATH = io.github.bfstats.dbstats.jooq.tables.RoundPlayerDeath.ROUND_PLAYER_DEATH;

    /**
     * The table <code>round_player_deploy_object</code>.
     */
    public static final RoundPlayerDeployObject ROUND_PLAYER_DEPLOY_OBJECT = io.github.bfstats.dbstats.jooq.tables.RoundPlayerDeployObject.ROUND_PLAYER_DEPLOY_OBJECT;

    /**
     * The table <code>round_player_medpack</code>.
     */
    public static final RoundPlayerMedpack ROUND_PLAYER_MEDPACK = io.github.bfstats.dbstats.jooq.tables.RoundPlayerMedpack.ROUND_PLAYER_MEDPACK;

    /**
     * The table <code>round_player_pickup_kit</code>.
     */
    public static final RoundPlayerPickupKit ROUND_PLAYER_PICKUP_KIT = io.github.bfstats.dbstats.jooq.tables.RoundPlayerPickupKit.ROUND_PLAYER_PICKUP_KIT;

    /**
     * The table <code>round_player_repair</code>.
     */
    public static final RoundPlayerRepair ROUND_PLAYER_REPAIR = io.github.bfstats.dbstats.jooq.tables.RoundPlayerRepair.ROUND_PLAYER_REPAIR;

    /**
     * The table <code>round_player_score_event</code>.
     */
    public static final RoundPlayerScoreEvent ROUND_PLAYER_SCORE_EVENT = io.github.bfstats.dbstats.jooq.tables.RoundPlayerScoreEvent.ROUND_PLAYER_SCORE_EVENT;

    /**
     * The table <code>round_player_team</code>.
     */
    public static final RoundPlayerTeam ROUND_PLAYER_TEAM = io.github.bfstats.dbstats.jooq.tables.RoundPlayerTeam.ROUND_PLAYER_TEAM;

    /**
     * The table <code>round_player_vehicle</code>.
     */
    public static final RoundPlayerVehicle ROUND_PLAYER_VEHICLE = io.github.bfstats.dbstats.jooq.tables.RoundPlayerVehicle.ROUND_PLAYER_VEHICLE;

    /**
     * The table <code>server</code>.
     */
    public static final Server SERVER = io.github.bfstats.dbstats.jooq.tables.Server.SERVER;

    /**
     * The table <code>topid</code>.
     */
    public static final Topid TOPID = io.github.bfstats.dbstats.jooq.tables.Topid.TOPID;
}
