/**
 * This class is generated by jOOQ
 */
package io.github.bfvstats.jooq.tables;


import io.github.bfvstats.jooq.DefaultSchema;
import io.github.bfvstats.jooq.Keys;
import io.github.bfvstats.jooq.tables.records.RoundPlayerScoreEventRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoundPlayerScoreEvent extends TableImpl<RoundPlayerScoreEventRecord> {

    private static final long serialVersionUID = 1379625605;

    /**
     * The reference instance of <code>round_player_score_event</code>
     */
    public static final RoundPlayerScoreEvent ROUND_PLAYER_SCORE_EVENT = new RoundPlayerScoreEvent();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RoundPlayerScoreEventRecord> getRecordType() {
        return RoundPlayerScoreEventRecord.class;
    }

    /**
     * The column <code>round_player_score_event.id</code>.
     */
    public final TableField<RoundPlayerScoreEventRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>round_player_score_event.round_id</code>.
     */
    public final TableField<RoundPlayerScoreEventRecord, Integer> ROUND_ID = createField("round_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>round_player_score_event.player_id</code>.
     */
    public final TableField<RoundPlayerScoreEventRecord, Integer> PLAYER_ID = createField("player_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>round_player_score_event.player_location_x</code>.
     */
    public final TableField<RoundPlayerScoreEventRecord, Float> PLAYER_LOCATION_X = createField("player_location_x", org.jooq.impl.SQLDataType.REAL.nullable(false), this, "");

    /**
     * The column <code>round_player_score_event.player_location_y</code>.
     */
    public final TableField<RoundPlayerScoreEventRecord, Float> PLAYER_LOCATION_Y = createField("player_location_y", org.jooq.impl.SQLDataType.REAL.nullable(false), this, "");

    /**
     * The column <code>round_player_score_event.player_location_z</code>.
     */
    public final TableField<RoundPlayerScoreEventRecord, Float> PLAYER_LOCATION_Z = createField("player_location_z", org.jooq.impl.SQLDataType.REAL.nullable(false), this, "");

    /**
     * The column <code>round_player_score_event.event_time</code>.
     */
    public final TableField<RoundPlayerScoreEventRecord, Timestamp> EVENT_TIME = createField("event_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>round_player_score_event.score_type</code>.
     */
    public final TableField<RoundPlayerScoreEventRecord, String> SCORE_TYPE = createField("score_type", org.jooq.impl.SQLDataType.VARCHAR.length(30).nullable(false), this, "");

    /**
     * The column <code>round_player_score_event.victim_id</code>.
     */
    public final TableField<RoundPlayerScoreEventRecord, Integer> VICTIM_ID = createField("victim_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>round_player_score_event.weapon</code>.
     */
    public final TableField<RoundPlayerScoreEventRecord, String> WEAPON = createField("weapon", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * Create a <code>round_player_score_event</code> table reference
     */
    public RoundPlayerScoreEvent() {
        this("round_player_score_event", null);
    }

    /**
     * Create an aliased <code>round_player_score_event</code> table reference
     */
    public RoundPlayerScoreEvent(String alias) {
        this(alias, ROUND_PLAYER_SCORE_EVENT);
    }

    private RoundPlayerScoreEvent(String alias, Table<RoundPlayerScoreEventRecord> aliased) {
        this(alias, aliased, null);
    }

    private RoundPlayerScoreEvent(String alias, Table<RoundPlayerScoreEventRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RoundPlayerScoreEventRecord> getPrimaryKey() {
        return Keys.PK_ROUND_PLAYER_SCORE_EVENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RoundPlayerScoreEventRecord>> getKeys() {
        return Arrays.<UniqueKey<RoundPlayerScoreEventRecord>>asList(Keys.PK_ROUND_PLAYER_SCORE_EVENT);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<RoundPlayerScoreEventRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<RoundPlayerScoreEventRecord, ?>>asList(Keys.FK_ROUND_PLAYER_SCORE_EVENT_ROUND_1, Keys.FK_ROUND_PLAYER_SCORE_EVENT_PLAYER_2, Keys.FK_ROUND_PLAYER_SCORE_EVENT_PLAYER_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoundPlayerScoreEvent as(String alias) {
        return new RoundPlayerScoreEvent(alias, this);
    }

    /**
     * Rename this table
     */
    public RoundPlayerScoreEvent rename(String name) {
        return new RoundPlayerScoreEvent(name, null);
    }
}
